### ISSUE TITLE
Month names are in the genitive case

### ISSUE THREAD

**Issue by antlu** [Hexlet/hexlet-cv#150]
Месяцы в периодах работы/обучения представлены в родительном падеже: мая, июня, июля.

> мая 2008 - июня 2009

Нужен именительный падеж: май, июнь, июль.

Наверняка возникнет конфликт с датами оставления комментариев, так как там указывается число, и ему нужен родительный падеж месяца, как сейчас.

> 05 февр., 23:02

Можно указывать эти даты в формате dd.mm.yy.

**Comment by morphizm** [comment]
Взял

**Comment by acidmaksim** [comment]
@antlu задача сделана?

**Comment by antlu** [comment]
Нет.

**Comment by usernaimandrey** [comment]
@acidmaksim Привет возьму в работу!

**Comment by usernaimandrey** [comment]
Issues можно закрыть, пр принят

**Comment by antlu** [comment]
Исправления только к новым записям применятся?

**Comment by usernaimandrey** [comment]
Почему к новым, ко всем, поменялось отображение, а в базе данных они все как были в одном формате так и остались, если я правильно ваш вопрос понял

**Comment by antlu** [comment]
Не заметил изменений.
https://cv.hexlet.io/resumes/1717

**Comment by usernaimandrey** [comment]
Ага понял, отображение дат, где информация о работе и учёбе, собственно это то и не поменял, пофиксим)

**Comment by usernaimandrey** [comment]
Посмотрите, теперь все должно быть норм)
