### ISSUE TITLE
Количество просмотров учитывает просмотры автора

### ISSUE THREAD

**Issue by SuchkovSergey** [Hexlet/hexlet-cv#162]
Возможно, в данном показателе лучше не учитывать просмотры автора, так как пока пишешь, сто раз перезаходишь и смотришь, что получилось.
Если данная информация присутствует для работодателей, то логичнее исключить возможность "накрутки просмотров" самого автора. В таком случае данный показатель будет объективнее

**Comment by frontstall** [comment]
https://github.com/Hexlet/hexlet-cv/pull/256

**Comment by seth2810** [comment]
@frontstall still actual.

**Comment by frontstall** [comment]
ПР актуален, но не принят мейнтейнерами. Нужно звать @mokevnin

**Comment by usernaimandrey** [comment]
Привет! Скажите эта задача актуальна?

**Comment by fey** [comment]
Надо обсудить задачку с Кириллом, потому что разговоры про это были, но вроде решили не фиксиь. Приду с ответом попозже @usernaimandrey

**Comment by fey** [comment]
Кажется пофикшено, нужно проверить.
