### ISSUE TITLE
Add a filtering, multiple tag system with autocomplete to Resumes.

### ISSUE THREAD

**Issue by alXmas** [Hexlet/hexlet-cv#18]
Предлагаю добавить систему тегов к резюме, чтобы можно было осуществлять по ней поиск.
Пример с `stackoverflow:`
<img width="1272" alt="Screen Shot 2019-09-09 at 2 50 20 PM" src="https://user-images.githubusercontent.com/25566849/64525128-35add400-d311-11e9-9e82-ab7619dc36c6.png">
 Эта фича будет полезна юзерам, которые прежде чем писать свой вопрос, захотят посмотреть чужие резюме по тегу и возможно сразу найти ответ на свой вопрос или получить идею, что можно добавить в свое резюме.

**Comment by grozwalker** [comment]
@acidmaksim посмотри, пожалуйста, этот ишьюс. Еще актуально делать фильтрацию?

**Comment by acidmaksim** [comment]
@grozwalker пока закроем ишью, чтобы не было дублей.  Фильтрацию обсужу это с Кириллом.
