### ISSUE TITLE
Ошибка при попытке удаления записи "Опыт работы"

### ISSUE THREAD

**Issue by AlexeyShobanov** [Hexlet/hexlet-cv#180]
В режиме редактирования существующего резюме, попытка удалить одну или несколько записей "Опыт работы" при сохранении приводит к ошибке
![Снимок экрана 2020-06-22 в 17 12 47](https://user-images.githubusercontent.com/11249101/85298895-4b117a80-b4ad-11ea-9e2c-bee8adf9273f.png)

**Comment by mokevnin** [comment]
fixed
