### ISSUE TITLE
Add search form for resumes.

### ISSUE THREAD

**Issue by alXmas** [Hexlet/hexlet-cv#19]
Предлагаю добавить строку поиска в шапку сайта. Чтобы пользователи могли искать по названию/тегам указанным в чужих резюме. Когда строка поиска будет пуста будут выводиться список всех резюме, которые выложены на обсуждение.
<img width="656" alt="Screen Shot 2019-09-09 at 3 08 48 PM" src="https://user-images.githubusercontent.com/25566849/64526215-c1c0fb00-d313-11e9-9599-f4cd07338b7a.png">

**Comment by Lodo4ka** [comment]
возьму в работу
