### ISSUE TITLE
Ошибка при попытке открыть резюме в статусе черновика

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-cv#192]
![image](https://user-images.githubusercontent.com/697178/93968321-c4f22200-fd82-11ea-8b34-fe6d036a3779.png)
Пример резюме https://cv.hexlet.io/resumes/55

**Comment by d3mash** [comment]
@fey а можно побольше контекста? это твое резюме или чужое? есть ли на черновые резюме ссылки с самого сайта?

**Comment by fey** [comment]
@d3mash ошибка при попытке просмотреть чужое резюме в статусе черновика.
Проявляется как минимум если посмотреть незалогиненым
https://cv.hexlet.io/resumes/250
https://cv.hexlet.io/resumes/55
Вот мои черные резюме, в гостевом режиме получаю ошибку We're sorry, but something went wrong.

**Comment by d3mash** [comment]
а ссылки в интерфейсе туда есть? @fey 

кажется, что в случае, если ты хочешь попасть в черновое резюме – нужно отдавать 404 или 403 (за исключением случаев, когда оно твое)

могу запилить

**Comment by fey** [comment]
Ссылки есть, например студент дает ссылку прямую или я оставлял там рекомендацию и у меня плашка с уведомлением в левом сайдбаре висит

**Comment by d3mash** [comment]
вообще мне кажется, что не должно быть ссылок туда) это ж черновик

**Comment by fey** [comment]
Ну вот пример, когда я оставил рекомендацию, а резюме скрыли.

**Comment by d3mash** [comment]
> Как минимум 500 ошибки не должно быть.

это-то да

**Comment by yulia633** [comment]
Большая просьба починить) Мне кажется, лучше сделать возможность, чтобы по ссылке можно было смотреть резюме в режиме черновика. Например, я только зарегистрировалась и хочу это резюме обсудить с наставником, а потом уже выкладывать на всеобщее обозрение. Спасибо!

**Comment by mokevnin** [comment]
fixed
