### ISSUE TITLE
Возможно некорректные фильтры на вкладках

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-cv#197]
В режиме гостя нахожусь на главной https://cv.hexlet.io/
Жму популярные, открывается https://cv.hexlet.io/?q%5Bpopular_gteq%5D=2021-01-03
Ничего не меняется.

Жму "новые", показывается, открывается https://cv.hexlet.io/?q%5Bcreated_at_gteq%5D=2021-01-09
Страница пустая.

**Comment by prio65** [comment]
какие пункты надо проверить:
популярные - здесь по логике должны быть сортировка по количеству просмотров, по убыванию
новые - сортировка по дате публикации, от новых к более старым
