### ISSUE TITLE
Add "skills" by which you can filter resumes

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-cv#213]
у HR потребность найти только те резюме, которые могут быть связаны с определенным стеком. Найти только rails разработчиков.
Можно добавить выбор заранее определенных навыков или стеков, по которым можно будет делать выборки 
Варианты реализации:
* Теги
* Поиск

**Comment by Alisa-V-H** [comment]
I am waiting=)

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/pull/413

**Comment by usernaimandrey** [comment]
Функционал добавлен, можно закрывать я думаю)
