### ISSUE TITLE
Возможность удалять комментарии/резюме

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-cv#215]
https://cv.hexlet.io/resumes/25#answer-231 пошел спам
19:22
нужна возможность мочить

**Comment by amshkv** [comment]
только не удалять, а переводить в архивные, которые не выводить на странице
удалять ничего не надо)

**Comment by amshkv** [comment]
![Uploading image.png…]()
:catshake:

**Comment by mokevnin** [comment]
Пока сделал так, если баним юзера, то все что он оставлял не выводится
