### ISSUE TITLE
Не работает вход через GitHub

### ISSUE THREAD

**Issue by Ivankalachikov** [Hexlet/hexlet-cv#230]
Как воспроизвести:

- зайти на [https://cv.hexlet.io/users/sign_in](https://cv.hexlet.io/users/sign_in)
- нажать на _Войти с помощью: GitHub_

что происходит:

- адрес меняется на _https://cv.hexlet.io/users/auth/github_
- в браузере отображается `Not found. Authentication passthru.`
- в консоли 404 ошибка:
`Request URL: https://cv.hexlet.io/users/auth/github
Request Method: GET
Status Code: 404 Not Found
Remote Address: 63.32.161.232:443
Referrer Policy: strict-origin-when-cross-origin`

**Comment by mokevnin** [comment]
fixed
