### ISSUE TITLE
Увеличить длину текста вакансии, который передаётся в RSS

### ISSUE THREAD

**Issue by kirill-chertkov** [Hexlet/hexlet-cv#235]
Сейчас в фид https://cv.hexlet.io/vacancies.rss передаётся мало информации, и чтобы понять, что там внутри, нужно открывать страницу с вакансией. Было бы хорошо передавать или весь текст вакансии, или раздел Общие сведения целиком

**Comment by mokevnin** [comment]
Увеличил до 400
