### ISSUE TITLE
поправить регистр в разделе вакансии

### ISSUE THREAD

**Issue by prio65** [Hexlet/hexlet-cv#238]
на страницах вакансий, в блоке "похожие вакансии" нужно поправить регистр у города
вот здесь https://prnt.sc/1eb5bpp
нужно сделать чтобы город был с большой буквы 

пример можно увидеть здесь https://cv.hexlet.io/vacancies/11

на странице с выборкой по технологиям, можно поправить регистр в заголовке h1 
https://cv.hexlet.io/vacancy_filters/technology-php 

вот здесь - https://prnt.sc/1ebeawa

Нужно чтобы технология вывалилась так как она заполнена в карточке или вся в верхнем регистре, и в идеале ещё добавить дефис 
чтобы получалось [технология]-разработчик

**Comment by mokevnin** [comment]
fixed
