### ISSUE TITLE
поправить метатеги 

### ISSUE THREAD

**Issue by prio65** [Hexlet/hexlet-cv#239]
description в профилях пользователей 

https://cv.hexlet.io/users/:id
шаблон: [id] | Профиль пользователя [имя пользователя] | Hexlet CV

страница выборки город + технология 

https://cv.hexlet.io/vacancy_filters/city-moskwa_level-junior_technology-javascript

в тегах в некоторых местах пропущены переменные 

title сейчас: Вакансии для Джуниор Javascript разработчиков в городе | Hexlet CV
нужно добавить город: Вакансии для Джуниор Javascript разработчиков в городе **[город]** | Hexlet CV

выборка по технологии 
https://cv.hexlet.io/vacancy_filters/technology-php

description сейчас: Актуальные вакансии для Php разработчиков . Работа для -программистов, подборка от редакции Hexlet CV
нужно добавить технологию: Актуальные вакансии для Php разработчиков . Работа для **[технология]**-программистов, подборка от редакции Hexlet CV

**Comment by mokevnin** [comment]
fixed
