### ISSUE TITLE
нужно проверить и поправить фильтры на главной

### ISSUE THREAD

**Issue by prio65** [Hexlet/hexlet-cv#240]
речь про вот эти ссылки https://prnt.sc/1ebnsbe

какие пункты надо проверить: 
популярные - здесь по логике должны быть сортировка по количеству просмотров, по убыванию 
новые - сортировка по дате публикации, от новых к более старым

**Comment by mokevnin** [comment]
> https://prnt.sc/1ebnsbe

Эта штука у меня не открывается

**Comment by prio65** [comment]
![image](https://user-images.githubusercontent.com/85234845/127114223-55482bc0-1e52-4267-8ec9-994457129b7b.png)

вот про них речь

**Comment by fey** [comment]
Это? https://github.com/Hexlet/hexlet-cv/issues/197

**Comment by prio65** [comment]
да, то же самое, тогда закрою чтобы не дублировать
