### ISSUE TITLE
исправить HTTP заголовок 

### ISSUE THREAD

**Issue by prio65** [Hexlet/hexlet-cv#242]
на странице https://cv.hexlet.io/vacancies отдается тип контента Content-Type: **application/rss+xml;** charset=utf-8

нужно исправить на Content-Type: text/html; charset=utf-8

**Comment by mokevnin** [comment]
Только что глянул: Content-Type: text/html; charset=utf-8

**Comment by prio65** [comment]
https://webmaster.yandex.ru/tools/server-response/?url=https%3A%2F%2Fcv.hexlet.io%2Fvacancies%20&user-agent=robot&if-modified-since= 
посмотри ответом сервера, яндекс её не хочет индексировать

**Comment by prio65** [comment]
перепроверил, при ручной проверке всё хорошо https://prnt.sc/1eqmp75
ответ сервера яндекс показывает что страница xml

**Comment by prio65** [comment]
такое бывает, давай попробуем ссылку на rss убрать из кода или изменить адрес фида, чтобы он не совпадал со страницей 
https://cv.hexlet.io/vacancies.rss

**Comment by mokevnin** [comment]
> давай попробуем ссылку на rss убрать из кода или изменить адрес фида, чтобы он не совпадал со страницей

На серверной стороне такой проблемы нет, оно не бывает просто так, тут либо бага во фреймворке, либо кривой код. В нашем случае код кривой код, просто по дефолту стоял формат rss. Я поправил.

**Comment by prio65** [comment]
всё ок
