### ISSUE TITLE
Make page number substitution in tags for pagination

### ISSUE THREAD

**Issue by prio65** [Hexlet/hexlet-cv#264]
у нас индексируемая пагинация и нужно уникализировать теги чтобы такие страницы не дублировали первые страницы 

сделать это можно следующим образом 

если в адресе страницы есть параметр ?page=, то в теги title и description подставлять "Cтраница [номер страницы] - "

получается следующие шаблоны: 
title: Cтраница [номер страницы] - [title первой страницы]
description: Cтраница [номер страницы] - [description первой страницы]

Важно:
подстановка должна быть именно в начало тега 

теги первой страницы должны оставаться без изменений (без подстановки номера)

примеры страниц где может быть пагинация
главная - https://cv.hexlet.io/?page=2 
вакансии - https://cv.hexlet.io/vacancies?page=2
теги в вакансиях - https://cv.hexlet.io/vacancy_filters/technology-rest?page=2

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/pull/399

**Comment by usernaimandrey** [comment]
Пул реквест принят, если больше пожеланий нет ишю можно закрывать)
