### ISSUE TITLE
Stack search (filtering) for employers 

### ISSUE THREAD

**Issue by Alisa-V-H** [Hexlet/hexlet-cv#283]
На данный момент у работодателя нет возможно отсортировать CV по языкам программирования, что несёт за собой много неудобств.

**Comment by fey** [comment]
Подскажи. на какой странице это нужно. Нужна сортировка или фильтрация?

**Comment by acidmaksim** [comment]
Пока сделать поиск по тегам, как это реализовано в вакансиях - https://cv.hexlet.io/vacancies
Но сделать нужно селект, в котором еще можно писать
<img width="292" alt="image" src="https://user-images.githubusercontent.com/77053797/191999595-61a0c505-420a-4f8e-9b40-2a3e294f92d3.png">

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/pull/413
