### ISSUE TITLE
Неверно отображается выбранная технология в фильтре поиска вакансий

### ISSUE THREAD

**Issue by ralder** [Hexlet/hexlet-cv#308]
например тут https://cv.hexlet.io/vacancy_filters/direction-devops_level-middle - в фильтре должен быть выбран devops а показывается выбранным всегда первый Yii

**Comment by LubaRo** [comment]
@ralder Да, похоже проблема в регистре вариантов, когда из урла парсим, то они все donwcase, а форме value не приведены к нижнему регистру, а отдаются как есть.
