### ISSUE TITLE
Add a mark to the list of jobs or employer

### ISSUE THREAD

**Issue by andrejs82git** [Hexlet/hexlet-cv#313]
Привет!

Заметил что если много рассылать свое резюме по списку работодателей, то через некоторое время начинается путаница. Кому было отослано резюме, а кому ещё нет.

Поэтому прошу добавить возможность оставлять личные пометки для вакансии или работодателя .

Например, можно будет написать - "отправил резюме 01.02.2022" .

**Comment by usernaimandrey** [comment]
Возьму в работу

**Comment by usernaimandrey** [comment]
По поводу реализации есть такая мысль:
- создам в БД сущность - "отклик" эта сущность будит связывать пользователя и вакансию на которую он откликнулся(естественно работодателю уведомление не отпраляется)
- создать в выпадающем меню опцию, что бы пользаватель мог просматривать и редактировать отклики

**Comment by usernaimandrey** [comment]
Данный функционал не нужен. Задачу можно закрыть
