### ISSUE TITLE
Fix the alignment of blocks in the resume list

### ISSUE THREAD

**Issue by kirill-chertkov** [Hexlet/hexlet-cv#314]
![Image 2022-02-04 22-23-21](https://user-images.githubusercontent.com/29174482/152590923-d1af7d2f-444c-44b2-8a18-3072ed9bfc01.png)

**Comment by denikeev** [comment]
могу решить эту проблему:
![problem](https://user-images.githubusercontent.com/46960223/196635629-a4029791-28af-49d1-afe3-a8dea64598ec.png)
есть два варианта:
I. установить колонке 16% ширины родителя
![solution2](https://user-images.githubusercontent.com/46960223/196636318-3e90104f-d5d4-4aa7-8b8a-66218fc1c9fd.png)

II. запретить колонке сжиматься и зафиксировать ширину в 100px
![solution1](https://user-images.githubusercontent.com/46960223/196636847-8af7fc64-f7df-4c35-9c06-ee502dc014b9.png)
класс flex-row у родительского контейнера лишний, его можно удалить, т.к. флекс по умолчанию row, минус этого способа, width нужно прописать в атрибут style

мобильную версию в обоих вариантах проверил, всё ок, жду обратной связи

**Comment by acidmaksim** [comment]
@Psixodelik может ты подскажешь ?

**Comment by denikeev** [comment]
@Psixodelik 
понятно, адаптив глянул, для первой колонки нужны будет три класса колонки coll, col-sm и col-lg, можно и двумя обойтись, но будет больше переносов: 
в среднем случае - перенос текста "Просмотров"
в редком случае - перенос количества "Просмотров"

как оформлю PR посмотришь ?
