### ISSUE TITLE
Добавить для студентов пометку, актуальна ли вакансия, или же она уже в архиве.

### ISSUE THREAD

**Issue by Alisa-V-H** [Hexlet/hexlet-cv#315]
В админке гна Hexlet CV отражается, если вакансия в архиве, но на сайте -- нет.
См. пример https://cv.hexlet.io/vacancies/385.
Данная вакансия в архиве, но студенту это никак не понять, потому что статус вакансии -- не отображается. 
Следовательно, как студенту понять, что вакансия всё ещё актуальна? Это нужно исправить, чтобы был виден статус по вакансии. 
![Screenshot_8](https://user-images.githubusercontent.com/79241796/153580439-da658607-3a77-42d7-a4a1-bce725209090.png)

**Comment by seth2810** [comment]
@mokevnin а кто закрывает issue?

**Comment by fey** [comment]
@Alisa-V-H посмотри, плз, если все ок - закрывай :)
