### ISSUE TITLE
Добавить градация "стажёр" в название вакансии. 

### ISSUE THREAD

**Issue by Alisa-V-H** [Hexlet/hexlet-cv#331]
На данный момент есть градация от джуна до синьора, поскольку на сайте публикуются и стажировки, что важно добавить градацию "стажёр", т.к. для некоторых компаний -- это важный и принципиальный момент. По сути, у стажёра з/п может отличаться от джуна, поэтому, чтобы не вводить в заблуждение ребят с Хекслета и не вызывать лишний негатив, добавим "стажёра". 
https://cv.hexlet.io/vacancies/453 -- правильнее будет -- Стажёр PHP (как пример).

**Comment by DimaKabanov** [comment]
Взял в работу

**Comment by DimaKabanov** [comment]
@fey issue можно закрыть
