### ISSUE TITLE
фильтра вакансий по направлению ноджс - коряво работает

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-cv#335]
![image](https://user-images.githubusercontent.com/697178/162224253-35ba6297-c2bb-4786-9d89-e9d9a5a429f2.png)

**Comment by Zigreal** [comment]
![Снимок экрана от 2022-06-10 11-03-25](https://user-images.githubusercontent.com/36897826/173020319-0380d7a3-91e0-4452-8b09-7d8d1511393b.png)

Не воспроизводится, мб починили?

**Comment by vasiliqa** [comment]
@fey а откуда у тебя точка в урле перед js? Верный урл https://cv.hexlet.io/vacancy_filters/direction-nodejs, у тебя https://cv.hexlet.io/vacancy_filters/direction-node.js

**Comment by seth2810** [comment]
@fey не пора ли закрывать? Фикс вылит. У меня баг не воспроизвелся.

**Comment by fey** [comment]
давай.
