### ISSUE TITLE
Add markdown editor

### ISSUE THREAD

**Issue by Alisa-V-H** [Hexlet/hexlet-cv#347]
Прописать маркдауны, чтобы студенты сразу видели и понимали, как их проставлять, например, ссылкой на проект.

**Comment by ralder** [comment]
ммм а можно подробнее? сейчас это описание не понятно

**Comment by acidmaksim** [comment]
@ralder здесь имелось ввиду, чтобы студент мог делать гиперссылки, потому сейчас длинные ссылки выглядят не очень красиво
<img width="643" alt="image" src="https://user-images.githubusercontent.com/77053797/189297498-c03db6ab-7fc0-4311-a103-c21785741c27.png">

**Comment by acidmaksim** [comment]
Сейчас на проекте уже есть поддержка markdown, но нужно добавить сделать так, чтобы все видели, что он есть и им можно пользоваться.
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/77053797/192007284-6e232705-ce37-40d2-b8c7-c49ed00f26cb.png">

Вот библиотека, которую можно добавить для этого -  https://github.com/nhn/tui.editor

**Comment by Lodo4ka** [comment]
пошел делать

**Comment by acidmaksim** [comment]
@Lodo4ka как успехи с задачей?

**Comment by Lodo4ka** [comment]
@acidmaksim делал другую задачу, ждал ее апрува и оказалось что не надо было. Эту скоро начну делать

**Comment by Lodo4ka** [comment]
@acidmaksim не получается добавить мардаун редактор https://github.com/nhn/tui.editor из-за проблемы с байндингом формы. Можно я добавлю https://guides.rubyonrails.org/action_text_overview.html ?
