### ISSUE TITLE
Add English locale

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-cv#349]

**Comment by Shamilist** [comment]
Привет!
Это же нужно делать с помощью i18next?
Сейчас на 3 проекте по фронту, могу взять его в работу?

**Comment by fey** [comment]
@Shamilist привет, проект hexlet-cv работает на Rails, там есть свой механизм для локализаций.
Если получится разобраться - то гуд, если нет - можно помочь с переводами (вычиткой, например)
https://guides.rubyonrails.org/i18n.html
Поэтому хорошо, если вы знаете хотя бы основы Rails. Плюс надо сделать переключалку языка (как на Code Basics)

**Comment by Shamilist** [comment]
@fey Спасибо за ответ, Николай! 
Мне бы сейчас закрепить знания по JS.
Решил, что сфокусируюсь на проекте codebattle, завтра у нас созвон.

**Comment by fey** [comment]
@Shamilist у нас много проектов на js =)
Посмотрите например hexletguides - там идет переезд на nextjs =)

**Comment by acidmaksim** [comment]
Работа ведется в #378 issue
