### ISSUE TITLE
Setting up notifications with Hexlet CV

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-cv#355]
Set up an email notification:

- Career counselor gets notified if student asks questions, basically writes something in the career counselor's comment on the Hexlet CV
- the student is notified that his or her CV has been reviewed

Email to which notifications should be sent employees: 
- [alisa.vorobeva@hexlet.io](mailto:alisa.vorobeva@hexlet.io)
- [ekaterina.savchenko@hexlet.io](mailto:ekaterina.savchenko@hexlet.io)

The following notifications should come in the email:

“Name Surname оставил комментарий - url” - for emplyoees

“Ваше резюме прошло ревью - url” - for students

**Comment by usernaimandrey** [comment]
Привет! Возьму в работу.
