### ISSUE TITLE
Change the 200 character limit to 400 characters

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-cv#356]
![image](https://user-images.githubusercontent.com/77053797/185401318-f169fc47-a800-40ea-b618-8b85857d5774.png)

**Comment by usernaimandrey** [comment]
Привет. Возьму в работу.

**Comment by coderhs** [comment]
You should close this since the issue is resolved.

**Comment by usernaimandrey** [comment]
@acidmaksim это ишью можно закрыть
