### ISSUE TITLE
New evaluation feature

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-cv#359]
Add a feature to have the resume evaluated on a 10-point scale for completion

**Comment by usernaimandrey** [comment]
Максим скажи где это должно отображаться и кто это должен видеть, все или только автор резюме?

**Comment by mike090** [comment]
Актуально?

**Comment by usernaimandrey** [comment]
> Актуально?

@mike090 я общался по поводу этой задачи с @acidmaksim, задача актуальна, но пока не понятно как реализовывать, с его слов  там задумка такая, что нужно подключить какую нибудь нейронку, которая будет сама оценивать твое резюме.

**Comment by grozwalker** [comment]
Нейронка Алиса!)

**Comment by usernaimandrey** [comment]
@grozwalker Aндрей можно такую https://www.cs.waikato.ac.nz/ml/weka/  в универе такую изучал:) opensource, а алиса платная)))
если серьезно то я думаю здесь можно и без нейронки)

**Comment by usernaimandrey** [comment]
Окей

**Comment by ssssank** [comment]
@usernaimandrey о, кажись ты это сделал =D
#516

**Comment by usernaimandrey** [comment]
ну в целом да
