### ISSUE TITLE
Hide comments from unauthorized users 

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-cv#361]
Make it so that only authorized users can leave and read comments under Hexlet CV. 

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/77053797/189389030-57d7aa10-1a63-4f1f-9d51-72164b05dd88.png">

**Comment by Amanetes** [comment]
Привет! Возьму в работу

**Comment by grozwalker** [comment]
Это разве еще не сделано?
