### ISSUE TITLE
 Set technologies alphabetically

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-cv#363]
Set technology sorting alphabetically, for ease of choice (https://cv.hexlet.io/vacancies):

<img width="733" alt="image" src="https://user-images.githubusercontent.com/77053797/190397660-41e7b279-59b1-41b6-b99a-e10ac7cf50f7.png">

**Comment by usernaimandrey** [comment]
Привет! Возьму в работу. Что обозначает бедж invalid

**Comment by usernaimandrey** [comment]
Привет можно закрывать, пр принят)
