### ISSUE TITLE
Add a link to CodeBattle

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-cv#366]
Add a link to CodeBattle when the checklist appears
https://github.com/Hexlet/hexlet-cv/pull/358

**Comment by grozwalker** [comment]
@acidmaksim непонятно что надо сделать

**Comment by acidmaksim** [comment]
@grozwalker тут нужно доработать описание, это по сути чеклист с карьерными целями.

**Comment by ssssank** [comment]
@fey кажется, это можно закрыть, так как будет реализовано в карьерном треке
