### ISSUE TITLE
Add a markdown editor similar to GitHub

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-cv#370]
Add a markdown editor similar to GitHub in the 'description' field
<img width="895" alt="image" src="https://user-images.githubusercontent.com/77053797/194331577-0545123f-dfe0-457b-a419-96d13de319c5.png">
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/77053797/194331837-b34658c3-f8e4-4620-ab40-b9943dbc664a.png">

**Comment by amrendranath** [comment]
@acidmaksim I would like to work on it. Can you assign this issue to me?

**Comment by warpedrhubarb** [comment]
I want to try to implement this. Is it ok to use a package [like this](https://yarnpkg.com/package/easymde)?

**Comment by acidmaksim** [comment]
@grozwalker подойдет пакет выше ?

**Comment by acidmaksim** [comment]
@grozwalker подскажи, пожалуйста

**Comment by acidmaksim** [comment]
https://github.com/nhn/tui.editor - вот есть еще альтернатива, наш прогер кидал, нашел только что

**Comment by acidmaksim** [comment]
@warpedrhubarb ты взялся за задачу?

**Comment by warpedrhubarb** [comment]
@acidmaksim смогу начать завтра, дам знать если появятся вопросы или не что-то не получится. альтернатива которую ты скинул выше выглядит отлично, воспользуюсь этим пакетом, спасибо!  👍

**Comment by warpedrhubarb** [comment]
@acidmaksim извините, не хватает времени и навыков Ruby, пока не готов выполнить данную задачу

**Comment by usernaimandrey** [comment]
взял в работу

**Comment by Lodo4ka** [comment]
дублируется задача и я ее взял https://github.com/Hexlet/hexlet-cv/issues/347

**Comment by Lodo4ka** [comment]
дублируется задача https://github.com/Hexlet/hexlet-cv/issues/347. Я ее брал ранее

**Comment by usernaimandrey** [comment]
@acidmaksim закрой тогда это issue, чтобы не было дублей

**Comment by acidmaksim** [comment]
#347 дубль
