### ISSUE TITLE
Put a check mark on all users

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-cv#373]
<img width="718" alt="image" src="https://user-images.githubusercontent.com/77053797/195026229-fb096488-2e1e-49ba-a9e3-b5323a2ca424.png">

**Comment by mike090** [comment]
У всех, включая вновь созданных?

**Comment by usernaimandrey** [comment]
Привет @mike090 да у всех пользователей нотфикация по дефолту должна быть включена. Когда обсуждали с @acidmaksim договорились так

**Comment by usernaimandrey** [comment]
@mike090 привет ты будешь эту задачу делать? @acidmaksim задача актуальна?

**Comment by mike090** [comment]
Прописать дефолтное значение в модель? Не уверен что правильно понял задание. Не буду

**Comment by usernaimandrey** [comment]
> Прописать дефолтное значение в модель? Не уверен что правильно понял задание. Не буду

Всё верно понял, чтобы у всех пользователей включая созданных по дефолту почтовая рассылка была включена, прописать дефолт в модели и миграцию. Тогда я возьму)

**Comment by mike090** [comment]
> включая созданных

Они точно будут рады?) Да, бери

**Comment by usernaimandrey** [comment]
Да я тоже об этом думал , но там одно два письма, когда карьерный консультант оставляет рекомендацию, так что думаю норм)

**Comment by usernaimandrey** [comment]
Функционал добавлен можно закрыть)
