### ISSUE TITLE
Make a tree structure of comments

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-cv#374]
<img width="634" alt="image" src="https://user-images.githubusercontent.com/77053797/195032046-42b83541-2b51-49b4-908b-733cba39d92b.png">

**Comment by usernaimandrey** [comment]
Небольшое уточнение: надо настроить почтовую рассылку так чтобы автор комментария получал уведомление, если его комментарий прокомментировали.

**Comment by usernaimandrey** [comment]
Взял в работу.
