### ISSUE TITLE
Make an English version of Hexlet-CV

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-cv#378]
- [x] #379
- [x] #380
- [x] #381
- [x] #382

**Comment by acidmaksim** [comment]
@amshkv посмотри, пожалуйста, ничего ли я не упустил. Еще подумаю, как поделить задачку с переводами

**Comment by usernaimandrey** [comment]
@amshkv или @grozwalker  скажи пожалуйста можно такой гем для перевода моделей затащить https://github.com/globalize/globalize

**Comment by grozwalker** [comment]
> @amshkv или @grozwalker скажи пожалуйста можно такой гем для перевода моделей затащить https://github.com/globalize/globalize

Здесь скорее политический момент, будем ли мы использовать возможность писать одну и туже вакансию на разных языках или может быть это будут совершенно два разных сайта и всякое такое.

@acidmaksim подскажи, пожалуйста, в какую сторону мы будет двигаться?

Пс сам гем прикольный, не видел его раньше

**Comment by usernaimandrey** [comment]
@grozwalker гем к сожалению не поддерживается вот такой рекомендуют сами разработчики https://github.com/shioyama/mobility
