### ISSUE TITLE
Set up a redirect

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-cv#381]
If you go via a direct link, you don't need to change the language. If you go through the home page, then check the language

**Comment by amshkv** [comment]
Example on code-basics
https://github.com/hexlet-basics/hexlet-basics/blob/36c8e1b669543b3795465ad9f954326e96df9cbd/app/controllers/web/application_controller.rb#L34
https://github.com/hexlet-basics/hexlet-basics/blob/main/app/controllers/web/locales_controller.rb

**Comment by usernaimandrey** [comment]
@amshkv скажи пожалуйста можно такой гем для перевода моделей затащить https://github.com/globalize/globalize

**Comment by amshkv** [comment]
а какую проблему ты хочешь решить с помощью этого гема?
ПыСы: там в ридми написано что гем не поддерживается

**Comment by usernaimandrey** [comment]
План действий:
Добавить аттрибут в locale в соответствующие модели
Написать миграцию что все сущности на данный момент имеют значение локали :ru

**Comment by grozwalker** [comment]
Похоже этот план действий не очень соответствует проблеме этого ишьюза. Здесь же говорится, что мы детектим язык только при переходе на главную страницу, получается нам надо понимать что это за страница и если главная - запускать логику редиректов

**Comment by usernaimandrey** [comment]
> Похоже этот план действий не очень соответствует проблеме этого ишьюза. Здесь же говорится, что мы детектим язык только при переходе на главную страницу, получается нам надо понимать что это за страница и если главная - запускать логику редиректов

@grozwalker это я просто не сюда написал это вот к этому относится https://github.com/Hexlet/hexlet-cv/issues/380, его уже смержили, посыл бый такой что когда вот этот пр примут https://github.com/Hexlet/hexlet-cv/pull/390 то ресурсы резюме и вакансии будут создаваться и в поле локаль будет устанавливаться текущая локаль и все выборки из БД будут делаться искодя из текущей локали

**Comment by usernaimandrey** [comment]
нет все норм
