### ISSUE TITLE
Add translations of texts and other things.

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-cv#382]
We will have a separation of translations, interface translation and everything else. This task can be broken down into several PRs. Who will do it, let me know.

**Comment by acidmaksim** [comment]
We will have a separation of translations, interface translation and everything else. This task can be broken down into several PRs. Who will do it, let me know.

**Comment by acidmaksim** [comment]
При переводе интерфейсов важно учитывать плюрализацию. 
Example: https://github.com/hexlet-basics/hexlet-basics/blob/main/config/locales/en.yml,

**Comment by acidmaksim** [comment]
When translating interfaces, it is important to consider pluralization. 
Example: https://github.com/hexlet-basics/hexlet-basics/blob/main/config/locales/en.yml

**Comment by askorutin26** [comment]
@acidmaksim Привет, хотел бы взять, посмотрел, большая часть интерфейса уже переведена, нужно посмотреть что еще не переведено? И по этому issue https://github.com/Hexlet/hexlet-cv/issues/379 - по умолчанию английская локаль, как я понял

**Comment by acidmaksim** [comment]
@askorutin26 как у тебя дела по этой задаче?

**Comment by askorutin26** [comment]
> @askorutin26 как у тебя дела по этой задаче? Тебе яснее стало после созвона ?

почти закончил, сейчас вношу изменения после ревью
