### ISSUE TITLE
Add field

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-cv#391]
Add field:
1. City/Город;

2. Relocation/Релокация:
- Ready in the country of residence/Готов в рамках страны проживания
- Not ready/Не готов
- Ready to go to another country/Готов в другую страну
![telegram-cloud-photo-size-2-5390888249968411343-y](https://user-images.githubusercontent.com/77053797/198221637-b04ef948-184a-4f40-b483-2480bdf9d210.jpg)

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/pull/396

**Comment by usernaimandrey** [comment]
пр принят issues можно закрыть я думаю
