### ISSUE TITLE
Add a resume search filter by stack

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-cv#392]

**Comment by kanigreg** [comment]
Взал в работу.

**Comment by kanigreg** [comment]
Есть пару вопросв:
- Я правильно понимаю, что нужно добавить фильрацию по навыкам указаным в резюме?
- Нужно ли добавлять теги навыков в резюме? Или реализовать фильтрацию поиском?
- Если попытаться реализовать навыки резюме в тегах, то как мигрировать существующие записи из текстового поля в теги? На данный момент навыки в резюме представлены в БД как текстовое поле. Теги в вакансиях реализованы как ассоциации к таблице. Проблема в том, что для тегов используется определенный формат записи, но в существующих резюме, формат навыков может быть произвольный.

**Comment by usernaimandrey** [comment]
@kanigreg привет посмотри в этот пр
https://github.com/Hexlet/hexlet-cv/pull/398
сдесь человек делает что то похожее возможно вам надо с ним синхронизироваться

**Comment by usernaimandrey** [comment]
> Есть пару вопросв:
> 
> * Я правильно понимаю, что нужно добавить фильрацию по навыкам указаным в резюме?
> * Нужно ли добавлять теги навыков в резюме? Или реализовать фильтрацию поиском?
> * Если попытаться реализовать навыки резюме в тегах, то как мигрировать существующие записи из текстового поля в теги? На данный момент навыки в резюме представлены в БД как текстовое поле. Теги в вакансиях реализованы как ассоциации к таблице. Проблема в том, что для тегов используется определенный формат записи, но в существующих резюме, формат навыков может быть произвольный.

можно сделать как это сделлано в вакансиях, что автор резюме сам тегировал его, но для этого тогда надо дополнительное поле в форме тогда, собственно как и в вакансиях

**Comment by grozwalker** [comment]
@acidmaksim посмотри, пожалуйста, этот ишьюс сделан или нет? На проде уже вижу, что есть фильтрация по направлению 
<img width="985" alt="image" src="https://user-images.githubusercontent.com/16976296/211856921-5467b211-0207-4e73-a722-99e0df5ac3ae.png">

**Comment by usernaimandrey** [comment]
@grozwalker Андрей фильтрацию по резюме делал же я, но я делал по вот этим двум issue
https://github.com/Hexlet/hexlet-cv/issues/213
https://github.com/Hexlet/hexlet-cv/issues/283

я уже даже и забыл что в этом issue что то комменировал

**Comment by usernaimandrey** [comment]
Пожалуйста актуализируйте все issues, потому что есть которые +/- повторяют функционал друг друга, просто открыты в разное время, вот например:
https://github.com/Hexlet/hexlet-cv/issues/18
https://github.com/Hexlet/hexlet-cv/issues/19
https://github.com/Hexlet/hexlet-cv/issues/213
https://github.com/Hexlet/hexlet-cv/issues/283
просто могут быть коллизии
