### ISSUE TITLE
Add notice in tg and slack

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-cv#394]
Make it so that the career track employee in the admin, when he repeatedly posted the same job, it will be added automatically to Slack and Telegram

**Comment by mike090** [comment]
Есть возможность увидеть код, выполняющий отправку новых вакансий в slack и tg?

**Comment by acidmaksim** [comment]
Это не происходит в коде вообще. В коде формируется рсс, а автоматизация забирает уже из фида просто. 
Добавить в cv что-то типа published_date, и заполнять ее при каждом опубликовании. 
Опубликовали новое резюме - дата обновилась, в rss пришло. 
Архивировали - ничего не случилось.
Разархивировали - снова поменяли дату публикации.

**Comment by mike090** [comment]
Я правильно понимаю последовательность?:
- в таблицу vacancies добавить поле last_published_at
- в модель Vacancy добавить event :restore переводящее вакансию из архивной в "на модерации". Сейчас после редактирования вакансия не попадает на модерацию. Это норм?
- в форму редактирования добавить сабмит поднимающий вакансию из архива и логику в Web::Account::VacanciesController#update
- датой публикации будет считаться дата отправки на модерацию или дата перехода в статус published ?
- во вьюхах web/shared/_vacancies.html.slim  и index.rss.builder датой публикации считать last_published_at

**Comment by acidmaksim** [comment]
@amshkv подскажи, пожалуйста

**Comment by amshkv** [comment]
> в таблицу vacancies добавить поле last_published_at

да

> в модель Vacancy добавить event :restore переводящее вакансию из архивной в "на модерации". Сейчас после редактирования вакансия не попадает на модерацию. Это норм?

это продуктовый вопрос, тут Максим уточнит и подскажет, пока можно идти по "старой схеме"

> в форму редактирования добавить сабмит поднимающий вакансию из архива и логику в Web::Account::VacanciesController#update

не уверен насчет реализации, но надо чтобы при переопубликовании (или перемодерации) менялся last_published_at
Не знаю как сделано сейчас, но звучит как селект со стейтом?

> датой публикации будет считаться дата отправки на модерацию или дата перехода в статус published ?
во вьюхах web/shared/_vacancies.html.slim и index.rss.builder датой публикации считать last_published_at

да, похоже на правду

**Comment by ralder** [comment]
дополню что у гема aasm есть опция timestamps https://github.com/aasm/aasm#timestamps

>>звучит как селект со стейтом?
Андрей, ты наверно имел ввиду селект с ивентами (правда его придется реализовывать вручную... и возможно проще просто отдельными кнопками сделать)

**Comment by amshkv** [comment]
окей, не учел что это не Хекслет :)
если проще отдельными кнопками, то давай для начала кнопками :)

**Comment by mike090** [comment]
ralder, спасибо за подсказку, очень кстати. Ихмо селект со стейтами в форме редактирования совсем не удобно. Что скажете по поводу отдельных(ого) экшна для архивирования/публикации/модерации вакансии? Если не ошибаюсь, сейчас изменение стэйта происходит в апдейт. Я к тому что для публикации или архивировании вакансии не всегда нужно ее редактировать. Тем более сейчас форма редактирования на три локтя вниз.
Ну и жду ответа от @acidmaksim, куда вакансию после апдейта, на модерацию или в паблиш?

**Comment by acidmaksim** [comment]
@mike090 вакансия должна сразу публиковаться

**Comment by mike090** [comment]
@acidmaksim 
> вакансия должна сразу публиковаться
ок. Еще уточню некоторые моменты:
- сейчас из архива вакансию может поднять только админ, норм?
- вакансия в статусе "опубликована", автор ее изменил. Дата публикации должна измениться?

**Comment by acidmaksim** [comment]
@mike090 да, вакансию публикует только админ. Дату тоже менять на актуалььную

**Comment by mike090** [comment]
что по поводу сортировки вакансий в /vacancies, /vacancies.rss ? Да и в аккаунте с админкой. Оставляю как есть?

**Comment by mike090** [comment]
> Это не происходит в коде вообще. В коде формируется рсс, а автоматизация забирает уже из фида просто.

@amshkv, правильно понимаю что автоматизация забирает из фида все, что опубликовано после её последней проверки?

**Comment by amshkv** [comment]
сейчас да, она забирает всё новое, что появилось (то чего не было в прошлой рассылке)
смотрит на поле guid и берет новые записи
можно передавать в этот guid время publish_date в виде timestamp (чтобы было уникальная запись)
или `id.timestamp` что-нибудь такое

**Comment by mike090** [comment]
кто ж знал. Предполагал что считает новыми все вакансии у которых created_at больше последнего запроса. Жду тогда конкретно что хотите в guid видеть

**Comment by amshkv** [comment]
`"{id}.{publish_date}"`

**Comment by mike090** [comment]
@amshkv, норм?
```
<item>
    <title>Yoptascript-developer</title>
    <description>...</description>
    <pubDate>Fri, 18 Nov 2022 14:29:51 +0000</pubDate>
    <link>http://localhost:3000/vacancies/250436259</link>
    <guid>250436259.2022-11-18 14:29:51 UTC</guid>
</item>
```
