### ISSUE TITLE
Ворос: Актуальность вакансий опубликованных более 6 месяцевназад

### ISSUE THREAD

**Issue by usernaimandrey** [Hexlet/hexlet-cv#414]
![IMG_20221213_142153](https://user-images.githubusercontent.com/48034349/207305402-1f9c0254-2921-4963-bc46-c2bb339412c5.png)
Сомневаюсь в актуальности вакансий опубликованных более 6 месяцев назад, возможно их стоит перенести в архив

**Comment by acidmaksim** [comment]
@usernaimandrey то имеешь ввиду, что после полугода переносить такие вакансии в архив автоматически?

**Comment by usernaimandrey** [comment]
В целом да можно и автоматизировать
