### ISSUE TITLE
On the jobs page, you need to fix the styles

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-cv#418]
On the [vacancies page](https://cv.hexlet.io/vacancies), you need to fix the styles. Tags are now going out of bounds

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/77053797/208686129-3e8c0b70-7070-4e0a-bd1e-bcedf469fbb0.png">
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/77053797/208686168-97457e93-d328-467b-a311-d25f27d56ff5.png">
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/77053797/208686193-d122d1dd-2c97-4a34-b5b9-3172b221ca37.png">

**Comment by usernaimandrey** [comment]
это мой косяк, не учел что тэгов может быт много, сечас по фиксим

**Comment by usernaimandrey** [comment]
fixed, можно закрыть
