### ISSUE TITLE
В редактировании существующей вакансии нельзя обновить «Сколько денег»

### ISSUE THREAD

**Issue by yaroslav** [Hexlet/hexlet-cv#423]
Firefox 108.0.1 (64-bit), macOS 13.1

Как повторить:

- Зарегистрированный пользователь посещает свои вакансии https://cv.hexlet.io/account/vacancies
- Редактирует ранее опубликованную вакансию со значением «на руки» в поле «сколько денег»
- Меняет на «до вычетов»
- Сохраняет

Ожидание:

- В просмотре вакансии сумма денег помечается как «до вычетов»

Реальность:

- В просмотре вакансии и при повторном редактировании сумма все еще помечена как «на руки»

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/pull/424

**Comment by usernaimandrey** [comment]
fixed

**Comment by yaroslav** [comment]
Благодарю
