### ISSUE TITLE
Fix the layout

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-cv#434]
Fix the layout. Now in some cases the answers and questions are not positioned correctly, we need to find why this is so and fix it. 
![image](https://user-images.githubusercontent.com/77053797/212367486-a985a0b0-2ccf-4770-b727-8f9bf861ac95.png)

How it should be
<img width="991" alt="image" src="https://user-images.githubusercontent.com/77053797/212368231-ac3b42d5-5a9e-4568-b275-fa26852c9759.png">

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/pull/435

**Comment by grozwalker** [comment]
Это при каком размере моника такое было?

**Comment by usernaimandrey** [comment]
> Это при каком размере моника такое было?

Да это я забыл добавить свойство flex-wrap, чтоб элементы в контейнере переносили, у меня такая же ситуация с вакансия и была

**Comment by grozwalker** [comment]
Это же уже пофиксили тоже?

**Comment by usernaimandrey** [comment]
> Это же уже пофиксили тоже?

@grozwalker ага уже сделали
