### ISSUE TITLE
Refactor docker support

### ISSUE THREAD

**Issue by amd-9** [Hexlet/hexlet-cv#443]
Вынес в issue список того, чего не хватает в данный момент на мой взгляд

- [ ] неработают тесты
- [ ] в `READMe.md` нет описания того как работать с проектам в контейнерах
- [ ] рефакторинг` Dockerfile`

Изложу своё виденье того как должна быть реализована поддержка докера.

1. `Dockerfile `должен быть самодостаточным, чтоб собрать `hexlet-cv` и стратуть без необходимости прописывать `CMD` или `ENTRYPOINT` в явном виде
2. При использовании контейнеризации в качетсве легковесного варианта для разработки в компоуз подставляется `volume `с исходным кодом на локальном диске
3. Должна быть возможность разрабатывать не имея установленного `Ruby` на локальной машине. Правишь код в текстовом редакторе, стартанул компоуз, получил результат

У нас как то разъехался процесс разработки надо данной фичей на два ПРа :) - #437 и #436

**Comment by amd-9** [comment]
@usernaimandrey @fey @grozwalker предлагаю коллективно обсудить

**Comment by fey** [comment]
тесты не работают, потому что в тестах подставляется `request.host = 'www.example.com'`, который по идее должен подтягиваться из енв файла `.env.test`, но нифига. Все подтягивается из `.env`. @grozwalker наверное твоя помощь нужна

>Dockerfile должен быть самодостаточным, чтоб собрать hexlet-cv и стратуть без необходимости прописывать CMD или ENTRYPOINT в явном виде

Сейчас все это есть, на самом деле. Только порядок слоев по-хорошему стоит поменять. Щас нода ставится ДО установки пееременных, типа директории проекта. Вероятность того, тчо версия ноды будет меняться выше, чем директория приложения и другие переменные.

По сути вся работа щас сводится к make compose-setup, make compose

Кстати мне кажется, что нужно через configus  указать нужный хост, а не обращаться к нему напрямую из контроллера. Тогда для прода можно будет указать хост, а для дева или теста будет просто значение в конфиге @grozwalker так же норм будет?

**Comment by fey** [comment]
Плюс докер композ конфиг стоит доработать, убрать env_file секцию имхо. Стоит гем dotenv, который подтягивает переменные из файла. 
Что еще. Щас не работает в докере разработка в контейнере фронтенда, потому что ничего не будет пересобираться. Для этого надо или сделать отдельный сервис или закинуть хероку в образ, чтобы просто запускать heroku local
Щас в композе большая страшная команда

**Comment by fey** [comment]
Ну и щас можно кодить спокойно, запуская все в контейнере. Вскоде выбрать remote containerк примеру

**Comment by usernaimandrey** [comment]
> тесты не работают, потому что в тестах подставляется request.host = 'www.example.com'

точно спасибо

**Comment by usernaimandrey** [comment]
> Кстати мне кажется, что нужно через configus указать нужный хост
да это было бы удобнее, на бэйсике переменные через configus поддтягиваются - очень удобно, единственное его сейчас нет на проекте

**Comment by usernaimandrey** [comment]
> Плюс докер композ конфиг стоит доработать, убрать env_file секцию имхо.
да это решает проблемму с тестами

**Comment by usernaimandrey** [comment]
@amd-9 доделаешь?  единственное я пофикшу запуск тестов) - это моя не доработка)

**Comment by amd-9** [comment]
> @amd-9 доделаешь? единственное я пофикшу запуск тестов) - это моя не доработка)

Да. Добавлю по пунктам

**Comment by grozwalker** [comment]
Сори, не увидел этот ишьюс. Проблема еще актуальна? вроде фиксили докер

**Comment by usernaimandrey** [comment]
Здесь вроде @amd-9 сказал до шлифует)

**Comment by grozwalker** [comment]
Но я все равно не понимаю что именно надо дошлифовать? вроде же все работает

**Comment by usernaimandrey** [comment]
> Но я все равно не понимаю что именно надо дошлифовать? вроде же все работает

по рекомендации @fey можно порядок слоев поменять и закинуть хероку в образ, что бы фронтенд пересобирался
