### ISSUE TITLE
Add template for issues

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-cv#447]
Add template for issues. 
This is necessary for a convenient description of new tasks or bugs. 

You can use this as a basis:
https://github.com/hexlet-rus/runit/tree/main/.github/ISSUE_TEMPLATE

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/77053797/215708306-2e7b5f9e-3817-47e0-9c9b-293a4095412b.png">

**Comment by Rishav1707** [comment]
Shall I work on this issue?
