### ISSUE TITLE
Bug: Фильтр по направлениям выходит за границы браузера

### ISSUE THREAD

**Issue by burenkov-anton** [Hexlet/hexlet-cv#450]
### Summary

Похоже что связано с длинной строкой в списке фильтра

![ФильтрНаправления](https://user-images.githubusercontent.com/11513918/216922942-0ce088d0-149b-442c-b394-2b19f6ffc5b1.png)

### Reproduction steps

```bash
На главной странице шелкаем на фильтр "Выберите направление"
```

### Expected result

Фильтр не выходит за границу браузера

### Actual result

Фильтр выходит за границу браузера

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/pull/451
