### ISSUE TITLE
Bug: не отображается text-area с markdown на странице редактирования резюме

### ISSUE THREAD

**Issue by andrew-walker91** [Hexlet/hexlet-cv#452]
### Summary

на странице редактирования резюме в разделе Описание перестало отображаться поле ввода. 

### Reproduction steps

```bash
1. в разделе мои резюме https://cv.hexlet.io/account/resumes
2. кликнуть на кнопку редактирования резюме
3. проскролить до блока Описание
```

### Expected result

блок отображается и доступен для редактирования

### Actual result

блок не отображается и не доступен для редактирования

![image](https://user-images.githubusercontent.com/109623320/217451914-4cff0068-f340-422e-b9d3-0da60ef61812.png)

![image](https://user-images.githubusercontent.com/109623320/217452194-4e5625f1-b6f8-4c79-b862-0a96cb7f3718.png)

### Browsers

Chrome

### OS

Linux

**Comment by usernaimandrey** [comment]
Протестировал в двух браузерах FireFox и Chrome, ОС Linux Ubuntu и Windows 10, баг не обнаружил, все работает корректно, попробуйте обновить браузер, если проблема сохранится напишите

**Comment by andrew-walker91** [comment]
Версия 110.0.5481.77 (Официальная сборка), (64 бит)

проблема осталась, может это конкретно в моем случае? при каждом предыдущем сохранении между строками добавлялось большое количество переносов и они сейчас отображаются в консоли. из за них может не отображаться?

в слаке скину запись экрана тебе

**Comment by usernaimandrey** [comment]
fix https://github.com/Hexlet/hexlet-cv/pull/461
