### ISSUE TITLE
Починить кнопку "Добавить вакансию" в ЛК админки. 

### ISSUE THREAD

**Issue by Alisa-V-H** [Hexlet/hexlet-cv#453]
### Problem description

На страницах админки https://cv.hexlet.io/admin в навигационном меню не работают dropdown-menu (добавление новых сущностей и настройки)
При нажатии добавляется `#` в ссылку, но само меню не появляется

![image (1)](https://user-images.githubusercontent.com/79241796/217465339-aeef46e5-772e-4209-ab5f-1a5bc3c8a53a.png)

### Proposed solution

Предположительно на этой странице не подключены или не работают bootstrap скрипты

**Comment by usernaimandrey** [comment]
Можно закрывать
