### ISSUE TITLE
Bug: При переходе на страницу "Forgot your password?" "Select" языка переключается на "RU".

### ISSUE THREAD

**Issue by 2KO1** [Hexlet/hexlet-cv#464]
### Summary

При переходе на страницу (https://cv.hexlet.io/users/password/new) для восстановления пароля, при выбранном английском языке, "Select" языка переключается на "RU", страница отображена на русском языке.

### Reproduction steps

```bash
- Перейти по ссылке (https://cv.hexlet.io/ru)
- В Select языка выбрать "Английский"
- Нажать кнопку "Sign in"
- Нажать кнопку "Forgot your password?"
```

### Expected result

"Select" языка = "EN", страница (https://cv.hexlet.io/users/password/new) отображена на английском языке

### Actual result

"Select" языка = "RU", страница (https://cv.hexlet.io/users/password/new) отображена на русском языке

### Browsers

Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)

### OS

Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)

**Comment by 2KO1** [comment]
Такая же проблема:
- "[Didn't receive confirmation instructions?](https://cv.hexlet.io/users/confirmation/new)" 
- "[Didn't receive unlock instructions?](https://cv.hexlet.io/users/unlock/new)"

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/pull/469

**Comment by usernaimandrey** [comment]
fixed, проверьте

**Comment by 2KO1** [comment]
@usernaimandrey проверил, исправлено
