### ISSUE TITLE
Bug: При выборе в "Select" языка "Английский" на странице "Восстановления пароля" осуществляется переход на главную страницу.

### ISSUE THREAD

**Issue by 2KO1** [Hexlet/hexlet-cv#466]
### Summary

На странице  (https://cv.hexlet.io/users/password/new) при выборе в "Select" языка "Английский" осуществляется переход на главную страницу (https://cv.hexlet.io/).

### Reproduction steps

```bash
- Перейти по ссылке (https://cv.hexlet.io/users/password/new)
- Выбрать "Английский" в "Select" языка
```

### Expected result

Страница (https://cv.hexlet.io/users/password/new) отображена на английском языке

### Actual result

Осуществляется переход на страницу (https://cv.hexlet.io/)

### Browsers

Google Chrome Версия 109.0.5414.120 (Официальная сборка), (64 бит)

### OS

Windows 10 Pro Версия 21H2 (сборка ОС 19044.2364)

**Comment by 2KO1** [comment]
Такая же проблема:
- [Didn't receive confirmation instructions?](https://cv.hexlet.io/users/confirmation/new)
- [Didn't receive unlock instructions?](https://cv.hexlet.io/users/unlock/new)

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/pull/468

**Comment by 2KO1** [comment]
@usernaimandrey эту проблему я так полагаю закрываем?

**Comment by usernaimandrey** [comment]
Да пока порешили редиректить на главную, так как когда сучности будут создаваться с учетом локали могут быть проблемы

**Comment by 2KO1** [comment]
В архив, не актуально
