### ISSUE TITLE
Bug: Нет английской локали на странице  получения инструкции разблокировки

### ISSUE THREAD

**Issue by polinatswet** [Hexlet/hexlet-cv#467]
### Summary

На странице (https://cv.hexlet.io/users/unlock/new)  нет английской локали. 
При выборе вкладки EN происходит переход на главную страницу (https://cv.hexlet.io).

### Reproduction steps

```bash
Выбрать английский язык - EN.
Открыть вкладку Sign up.
Открыть вкладку Didn't receive unlock instructions?
Выбрать английский язык - EN.
```

### Expected result

Отображение на английском языке страницы https://cv.hexlet.io/users/unlock/new

### Actual result

Отображается следующий текст и вкладки:
Выслать подтверждение заново
Email *
Войти
Регистрация
Забыли пароль?
Не получили подтверждение?
Войти с помощью: GitHub

После отображения текста на русском при выборе вкладки EN происходит переход на главную страницу (https://cv.hexlet.io).

### Browsers

Firefox, Chrome, Safari

### OS

Mac

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/pull/469

**Comment by usernaimandrey** [comment]
fixed проверяйте

**Comment by polinatswet** [comment]
<img width="993" alt="Снимок экрана 2023-02-28 в 11 24 45" src="https://user-images.githubusercontent.com/120312860/221783406-9caf4274-c4dc-48fa-8017-571a47435f45.png">
