### ISSUE TITLE
 Bug: Заголовок "комментарии" не переведен на английский.

### ISSUE THREAD

**Issue by Germankhz** [Hexlet/hexlet-cv#471]
### Summary

В английской версии при просмотре резюме у поля "Комментарии" заголовок отображается на русском.

### Reproduction steps

```bash
1. Перейти по ссылке https://cv.hexlet.io/resumes/2135
2. Выбрать версию сайта на английском языке.
3. Проследовать вниз странице до поля "Комментарии".
```

### Expected result

Заголовок поля "Комментарии" отображается на английском языке.

### Actual result

Заголовок поля "Комментарии" отображается на русском языке.
![Снимок1](https://user-images.githubusercontent.com/119713022/219824427-56340798-b2e6-4924-b987-e13b4ea91cc2.JPG)

### Browsers

Chrome

### OS

Windows

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/pull/470/files

**Comment by usernaimandrey** [comment]
![image](https://user-images.githubusercontent.com/48034349/221658741-38904b06-d0d3-4b98-a6b3-5dc87f0502e0.png)
тут тоже по фиксили
