### ISSUE TITLE
Bug: Частично нет английской локали в заголовке на странице поиска работы

### ISSUE THREAD

**Issue by borizi** [Hexlet/hexlet-cv#473]
### Summary

Частично нет английской локали в заголовке на странице поиска работы

### Reproduction steps

```bash
1. Открыть страницу "Jobs for developers" https://cv.hexlet.io/vacancies
2. Написать "Москва" в поле "City".
```

### Expected result

Заголовок "Vacancies for developers..." полностью переведен на английский язык.

### Actual result

Заголовок "Vacancies for developers..." частично переведен на английский, фраза "в городе" на русском.

![Нет локализации в заголовке на странице поиска работы_](https://user-images.githubusercontent.com/64551423/219869781-f61685f1-168e-40eb-89cc-37d2f834152c.jpg)

### Browsers

Chrome
Версия 109.0.5414.120 (Официальная сборка), (64 бит)

### OS

Windows 11 Pro 22H2
Сборка 22621.1265

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/pull/481
