### ISSUE TITLE
Bug: Перебрасывает на русскую версию сайта при авторизации через Гитхаб

### ISSUE THREAD

**Issue by borizi** [Hexlet/hexlet-cv#474]
### Summary

Перебрасывает на русскую версию сайта при авторизации через Гитхаб

### Reproduction steps

```bash
1. Открыть страницу "Log in" https://cv.hexlet.io/users/sign_in
2. Нажать "Sign in with GitHub".
3. Авторизоваться под своим логином в GitHub.
```

### Expected result

После авторизации происходит переход обратно на английскую версию сайта.

### Actual result

После авторизации происходит переход на русскую версию сайта:

![Перебрасывает на русскую версию сайта при авторизации через Гитхаб](https://user-images.githubusercontent.com/64551423/219870815-225d4e1e-84e5-4b11-97d8-52d6e6894a63.jpg)

### Browsers

Chrome
Версия 109.0.5414.120 (Официальная сборка), (64 бит)

### OS

Windows 11 Pro 22H2
Сборка 22621.1265

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/pull/482

**Comment by usernaimandrey** [comment]
вроде пофиксил, проверьте все нормально работает

**Comment by borizi** [comment]
Нет, всё-равно перебрасывает на русскую версию.

**Steps to reproduce:**

1. Скопировать адрес страницы авторизации: https://cv.hexlet.io/users/sign_in
2. Вставить в адресную строку в браузере и перейти на страницу
3. Нажать на "Sign in with GitHub"

**Actual result:**
Открывается русская версия сайта.

![Перебрасывает на русскую версию сайта при авторизации через Гитхаб 2](https://user-images.githubusercontent.com/64551423/220872660-2709e8f7-a63a-462e-b281-7a737e92809d.jpg)

![Перебрасывает на русскую версию сайта при авторизации через Гитхаб 2_2](https://user-images.githubusercontent.com/64551423/220872675-7b4bc223-fb85-4d1c-a26b-68abbf58486a.jpg)



---

Но если изначально находиться на главной странице, с неё перейти на страницу авторизации и авторизоваться через Гитхаб, то действительно открывается английская версия.

**Comment by ssssank** [comment]
@usernaimandrey посмотри, пожалуйста

**Comment by usernaimandrey** [comment]
@ssssank этот баг остался, посмотрю

**Comment by polinatswet** [comment]
- Баг воспроизводится.

**Summary**
При авторизации через GitHub с англоязычной версии сайта происходит переход на русскую локаль

**Reproduction steps**
1. Открыть страницу https://cv.hexlet.io/users/sign_in
2. Нажать  [Sign in with GitHub](https://cv.hexlet.io/users/auth/github)

**Actual result**
Русскоязычная версия сайта. Вывод сообщения - Вход в систему выполнен с учетной записью из Github.

**Expected result**
При авторизации через GitHub с англоязычной версии сайта сохраняется английская локаль

**Browsers**
Safari Версия 16.4 (18615.1.26.11.23)
Chrome Версия 113.0.5672.92 (Официальная сборка), (arm64)
macOS Ventura 13.3.1 (22E261)


https://github.com/Hexlet/hexlet-cv/assets/120312860/6faf3ef4-ce31-4481-9a4c-626b76df95bb


- Баг НЕ воспроизводится в следующем случае:

Reproduction steps
1. Открыть https://cv.hexlet.io/ru
2. Нажать кнопку "Английский"
4. Нажать кнопку "Sign in"
5. Нажать [Sign in with GitHub](https://cv.hexlet.io/users/auth/github)

Actual result
Англоязычная версия сайта. Вывод сообщения -Successfully authenticated from Github account.
