### ISSUE TITLE
Bug: Всплывающая подсказка "Выберите один из пунктов списка" не переведена на английский язык

### ISSUE THREAD

**Issue by Germankhz** [Hexlet/hexlet-cv#477]
### Summary

На странице создания нового резюме (английская версия сайта) при наведении курсора на поле обязательное для заполнения (содержащее выпадающий список) появляется всплывающая подсказка на русском языке "Выберите один из пунктов списка"
![Снимок1](https://user-images.githubusercontent.com/119713022/219908417-c3488e13-6ba7-47aa-901d-1cf865150151.JPG)

### Reproduction steps

```bash
1. Перейти на страницу https://cv.hexlet.io/account/resumes/new
2. Переключить версию сайта на английский язык
3. Навести курсор мыши на поле, отмеченное * -  обязательное для заполнения содержащее выпадающий список (Languages)
```

### Expected result

Появляется всплывающая подсказка на английском языке "Choose the list's item"

### Actual result

Появляется всплывающая подсказка на русском языке "Выберите один из пунктов списка"

### Browsers

Chrome

### OS

Windows

**Comment by borizi** [comment]
Это "подсказки" браузера, переключите интерфейс хрома на английский — они станут на английском. 
В #476 аналогично.

**Comment by Germankhz** [comment]
> Это "подсказки" браузера, переключите интерфейс хрома на английский — они станут на английском. В #476 аналогично.

Не разобрался слегка)) звиняюсь!
