### ISSUE TITLE
Feature Request: Автоматическое архивирование вакансий

### ISSUE THREAD

**Issue by Alisa-V-H** [Hexlet/hexlet-cv#480]
### Problem description

На данный момент на Hexlet CV большое количество вакансий, многие из них уже не актуальны, но они продолжают висеть на сайте, как "Активные". 

### Proposed solution

Все вакансии, через 2 недели после публикации уходят автоматом в архив. 

Такой подход:
1. Снимет рукопашку. Не придётся отслеживать все вакансии, ходить по компаниям и уточнять, активна ли её вакансия (тем более если учесть, что часть компаний -- это не партнёр Хекслета)
2. Уберёт "человеческий фактор". Если неактуальность вакансии проглядели -- она автомат заархивируется
3. Уберёт вопросы от студентов: "А эта вакансия активна?", следовательно уберём дополнительную операционку, в виде: пойти к компании, уточнить, проверить, вернуться к студенту. 

Более того, на данный момент на сайте скопилось большое количество вакансий,  и нет ресурса и времени, чтобы пройти по каждой из вакансий и уточнить её статус.

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/issues/414

**Comment by mokevnin** [comment]
Ага, давайте сделаем.

**Comment by fey** [comment]
Алиса, может ли вакансия выйти из архива? Как пример в ноушене у Хекслета https://www.notion.so/c6406ed8890747e690d32b050faf42c2
Кто её оттуда достает? (вероятнее только админ)
Или создается новая сущность?
Могут ли быть вакансии, у которых срок актуальности должен быть больше 2 недель?

**Comment by usernaimandrey** [comment]
> Или создается новая сущность

Можно как вариант сделать возможность для человека/компании который создал вакансию, обновить ее, если она актуальна, или по прошествию 2- х недель отправить в архив

**Comment by fey** [comment]
Договорились и обсудили, что отдельная вакансия не создается. 
При необходимости компания обращается к админу и админ (карьерный менеджер) достает вакансию из архива.
Если вакансия опубликована, то компания не может вносить в неё изменения.

**Comment by usernaimandrey** [comment]
> Если вакансия опубликована, то компания не может вносить в неё изменения.

Сейчас это можно делать, если резюме опубликованно, можно его редактировать, единственное не обновляется дата публикации

**Comment by fey** [comment]
да, заведу отдельную таску.

**Comment by usernaimandrey** [comment]
> да, заведу отдельную таску.

ок

**Comment by fey** [comment]
@Alisa-V-H сделоли, проверяй.

**Comment by Alisa-V-H** [comment]
Ok!
