### ISSUE TITLE
Split the contact field of a vacancy into two fields - telegram and phone number

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-cv#498]
### Problem description

We have ugly contact field on Hexlet CV - https://cv.hexlet.io/

Telegram and phone number inside single field. 

---

У нас очень некрасиво и неудобно смотрится поле с контактами на Hexlet CV.
Всё идёт сплошняком, одной линией, что нечитабельно ни для нас, ни для рекрутера. 
![image](https://user-images.githubusercontent.com/697178/225968667-ba815b2f-2d85-4416-8fe9-33818dcef17a.png)

### Proposed solution

Task: split field into two - telegram contact (text field), and phone number,

All old data must remain in the Telegram field so you don't lose it

---

Разделяем поле на два. Будет в БД, например как у вакансий.

![image](https://user-images.githubusercontent.com/697178/225968831-494c4fe5-4be4-4e37-8c49-26ecc17f9072.png)

**Comment by Aaryanpal** [comment]
Hi @fey 
U would like to contribute to this, bit it's bit difficult to understand what you actually want. Could you please describe in English

**Comment by fey** [comment]
@Aaryanpal hello thanks for your interest.
i have updated Issue, translated to english. Has it become clearer what needs to do?

**Comment by Aaryanpal** [comment]
Hi @fey 
That's great assign this ticket to me so that u can work. I will let you know if I run into an issue, i hope that's not a problem?

**Comment by fey** [comment]
@Aaryanpal Yeah, no problem. Ask questions if you have trouble. Do you think you can get it done by the end of the week? :)

**Comment by fey** [comment]
@Aaryanpal hi, how its going? Need help?

**Comment by Aaryanpal** [comment]
Sorry @fey, for responding so late i will let you know by EOD

**Comment by fey** [comment]
@Aaryanpal hi, need some help?
Our hr manager waiting %)

**Comment by Aaryanpal** [comment]
@fey on this issue

**Comment by Aaryanpal** [comment]
Hey @fey 
What i am able to understand this that,
User has entered the telegram link and phone number in the **contact-information field ** and when it's getting rendered it shows both of it in the one field under **contact-information** , 
So one way is  we can provide extra fields for telegram link and phone number under the **NEW Resume **
Any other idea@fey

**Comment by usernaimandrey** [comment]
Hello @Aaryanpal , yes, you are absolutely right, you need to add additional fields to the resume model, such as for example: contact_email , contact_phone , contact_telegret

**Comment by usernaimandrey** [comment]
> Hello @Aaryanpal , yes, you are absolutely right, you need to add additional fields to the resume model, such as for example: contact_email , contact_phone , contact_telegret

**Comment by Aaryanpal** [comment]
okay, @usernaimandrey , i will drop the PR by EOD

**Comment by fey** [comment]
Hi, we need this fix asap. I give task to @usernaimandrey

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/pull/501
