### ISSUE TITLE
Bug: не сохраняются все поля при редактировании резюме, если попытаться сохранить с невалидным полем

### ISSUE THREAD

**Issue by ssssank** [Hexlet/hexlet-cv#518]
### Summary

Если попытаться опубликовать резюме с незаполненным или некорректно заполненным полем "Описание", то поля Тэги навыков, Направление, а также все созданные места работы и учебы не сохраняются. Страница перезагружается, в форме подсвечивается ошибка в поле "Описание", часть полей остаются заполненными, но не все

### Reproduction steps

```bash
1. Создать и заполнить резюме
2. Поле "Описание" не заполнять
3. Нажать "Опубликовать"
```

### Expected result

При любых ошибках сохранять все заполненные поля

### Actual result

Не все данные, указанные при заполнении формы сохраняются

**Comment by maddbuzz** [comment]
https://cv.hexlet.io/

**Comment by maddbuzz** [comment]
Приветствую. На cv.hexlet.io такой баги не наблюдаю.
А локально последнюю версию репо проверить не могу, т.к. у вас уже Ruby 3.2.2, а у меня ASDF - в нем выше 3.2.0 пока ничего нет.

**Comment by ssssank** [comment]
@maddbuzz кажется понял, при каком условии случается баг: если резюме уже было опубликовано

**Comment by trufanovnik** [comment]
Все проверил с ласт версией. Все ок, формы остаются заполненными.

**Comment by ssssank** [comment]
Даже при изменении уже сохранённого резюме? :thinking:

**Comment by trufanovnik** [comment]
так чот не могу его редактировать. проверю вьюхи еще и отпишусь чо как

**Comment by trufanovnik** [comment]
> Даже при изменении уже сохранённого резюме? 🤔

Угу, все сохраняется.  Не сразу нашел кнопку редактирования (ток при просмотре титульника, а хотелось бы внутри сивихи, хотя мб я ее там не заметил).

**Comment by ssssank** [comment]
А вы меняете содержимое поля "Описание", так чтобы не прошла его валидация? Можно буквально стереть всё или оставить короткое сообщение

**Comment by maddbuzz** [comment]
само собой

**Comment by trufanovnik** [comment]
Поле и полностью очищал и не валидное делал. Прост ошибка без удаления других полей.

**Comment by usernaimandrey** [comment]
Баг, наблюдается при обновлении резюме, если какое то из полей будет не валидным(но непустым) то все новые изменения будут сброшенны! Соответственно надо сделать чтобы внесенные изменения сохранялись
