### ISSUE TITLE
Bug: Не отмечены обязательными к заполнению поля на странице создания вакансии

### ISSUE THREAD

**Issue by polinatswet** [Hexlet/hexlet-cv#549]
### Summary

Невозможно опубликовать вакансию с незаполненными полями: "Cайт компании",  "Зарплата от",  "Зарплата до".
Но в качестве обязательных эти поля не отмечены. Пользователь вынужден возвращаться к редактированию.

### Reproduction steps

```bash
1. Авторизоваться на сайте.
2. Нажать кнопку "Добавить", выбрать вкладку "Вакансию".
3. Заполнить все поля, отмеченные знаком "*".
4. Нажать кнопку "Создать"
```

### Expected result

Вакансия создана.

### Actual result

Вакансия не создана. Вывод сообщения: "Не удалось создать вакансию... Проверьте данные в форме и попробуйте еще раз." Незаполненные поля без " * " отмечены красной рамкой и подсказкой. 
 
<img width="1379" alt="Снимок экрана 2023-05-09 в 14 36 43" src="https://github.com/Hexlet/hexlet-cv/assets/120312860/79387960-0d71-4b74-8cbd-f69312bff5c9">

<img width="1379" alt="Снимок экрана 2023-05-09 в 14 37 01" src="https://github.com/Hexlet/hexlet-cv/assets/120312860/08b64643-5034-4185-86b6-8f841c4e558b">

### Browsers

Chrome, Safari

### OS

Mac

**Comment by usernaimandrey** [comment]
Тут тоже уточню) Валидация на эти поля стоит условная и она отключается если выбран тип запроботной платы по договоренности, но тип по договоренности включен только у админов, возможно стоит сделать hint под инпутом в котором уточнить что поле обязательно.

**Comment by polinatswet** [comment]
https://github.com/Hexlet/hexlet-cv/issues/557

**Comment by polinatswet** [comment]
partially reproduced https://github.com/Hexlet/hexlet-cv/issues/627
