### ISSUE TITLE
Feature request: Отсутствует кнопка "Опубликовать" в форме редактирования вакансии

### ISSUE THREAD

**Issue by polinatswet** [Hexlet/hexlet-cv#550]
### Problem description

В разделе "Мои вакансии"  пользователю доступно редактирование архивной вакансии. Есть кнопка "Изменить", и после ее нажатия выводится сообщение "Вакансия обновлена". Но опубликовать архивную вакансию невозможно. 

### Proposed solution

Вариант 1 - убрать кнопки редактирования и изменения в архивных вакансиях.
Вариант 2 - добавить функцию публикации архивных вакансий.

**Comment by usernaimandrey** [comment]
Тут стоит уточнить один момент, пользователь(компания который) который размещает вакансию самотоятельно ее опубликовать не может(и архивную в том числе), вакансия публикуется только после модерации админом, после того как вакансия опубликованна она через месяц автоматически отправляется в архив, если вакансию надо вернуть из архива то пользователь(компания) может внести в архивную вакансию необходимые правки и только после модерации она снова будет опубликованна. По этому думаю пока в этом нет необходимости

**Comment by polinatswet** [comment]
вакансию публикует модератор.
