### ISSUE TITLE
Feature request: Добавление подсказки про обязательное заполнение полей при создании вакансии

### ISSUE THREAD

**Issue by polinatswet** [Hexlet/hexlet-cv#557]
### Problem description

Кнопка создания вакансии. Отмечены в качестве обязательных к заполнению знаком " * " следующие поля:
уровень, тип занятости, валюта, должность, компания, обязанности.
НЕ отмечены в качестве обязательных:
 - Cайт компании,
 - Зарплата от, 
 - Зарплата до.
Если их пропустить - произойдет вывод сообщения: "Не удалось создать вакансию... Проверьте данные в форме и попробуйте еще раз."
Пользователь вынужден возвращаться к редактированию.
Валидация на эти поля стоит условная и отключается если выбран тип зарплаты по договоренности, но тип по договоренности включен только у админов
Reproduction steps:
1. Авторизоваться на сайте.
2. Нажать кнопку "Добавить", выбрать вкладку "Вакансию".
3. Заполнить все поля, отмеченные знаком "*".
4. Нажать кнопку "Создать"
Expected result - вакансия создана.

<img width="1379" alt="237076907-79387960-0d71-4b74-8cbd-f69312bff5c9" src="https://github.com/Hexlet/hexlet-cv/assets/120312860/7e7bed5c-1e69-4dd8-b00e-83639725fa19">

<img width="1379" alt="237076917-08b64643-5034-4185-86b6-8f841c4e558b" src="https://github.com/Hexlet/hexlet-cv/assets/120312860/e24ade9a-d5b2-44f2-9c02-771e290ed38f">

### Proposed solution

Добавить подсказку и отметку об обязательности заполнения полей.

**Comment by PavelKonkin** [comment]
Взял  в работу. 
А простым пользователям - не админам, специально убрали возможность выбирать тип зарплаты по договоренности?
У полей зарплата от и зарплата до обязательность заполнения зависит от друг друга и от типа зарплаты. Наверное не получится менять динамически отображение обязательности их заполнения.
