### ISSUE TITLE
Неправильное обозначение иностранного языка в английской версии сайта.

### ISSUE THREAD

**Issue by DmitriiGoltsov** [Hexlet/hexlet-cv#575]
### Problem description

В английской версии сайта при создании резюме имеется графа "Languages", где в выпадающем меню можно выбрать свой уровень владения языком. При этом, в отличии от русской версии сайта, графа в своём названии не содержит указания на то, о владении каким языком идёт речь. В итоге резюме выглядит как на приложенном скриншоте, то есть неинформативно и даже глупо. 

![Выделение_045](https://github.com/Hexlet/hexlet-cv/assets/118078412/43972785-9b5a-475e-a853-03cac9968810)

### Proposed solution

Нужно либо переименовать графу аналогично русскому варианту, где она называется "Владение английским языком", либо же в целом добавить возможность в резюме указывать несколько языков, которыми владеет человек, т.е., чтобы графы выглядели как-то так:

English language - fluently speaking
Russian language - native speaker
etc.

**Comment by fey** [comment]
Решили в англоязычной версии удалить это поле. Т.е. для тех, кто пользовуется hexlet-cv в англоязычном разделе, это поле скрыто. 
@PavelKonkin ожно взять изи-пизи задачку.
