### ISSUE TITLE
Bug: Отображение системного сообщения после редактирования и публикации резюме

### ISSUE THREAD

**Issue by AllIzm** [Hexlet/hexlet-cv#576]
### Summary

При обновлении, сохранении и публикации резюме после комментария Tota AI появляется системно-непереводимая надпись.
![indefined text Hexlet CV](https://github.com/Hexlet/hexlet-cv/assets/121917310/c4670660-fc7e-4dfc-a6bc-a1fbc3eab069)

**Browsers**
Google Chrome 113.0.5672.127 (Официальная сборка), (64 бит)
Mozilla Firefox 113.0.1 (64-разрядный)

**OS**
ОС Windows 11 22H2

### Reproduction steps

```bash
1. Нажать иконку редактирования уже опубликованного резюме.
2. Изменить/отредактировать поля.
3. Нажать кнопку Опубликовать.
```

### Expected result

При публикации резюме появляется уведомлении об успешном сохранении / публикации резюме на русском языке.

### Actual result

При публикации резюме появляется непереведенное системное уведомление

### Browsers

Chrome

### OS

Windows

**Comment by PavelKonkin** [comment]
Взял в работу
