### ISSUE TITLE
Bug: Орфографическая ошибка в названии кнопки Career path

### ISSUE THREAD

**Issue by polinatswet** [Hexlet/hexlet-cv#609]
### Summary

В слове "Career" вторая и третья буквы переставлены местами.
The second and third letters are swapped in the word "Career".

### Reproduction steps

```bash
1. Открыть https://cv.hexlet.io/
2. Авторизоваться.
3. Открыть в личном кабинете Career path -  https://cv.hexlet.io/account/members
4. Найти выделенное синим цветом поле Career path.
```

### Expected result

C**ar**eer path

### Actual result

C**ra**eer path

<img width="1420" alt="Снимок экрана 2023-06-16 в 19 32 02" src="https://github.com/Hexlet/hexlet-cv/assets/120312860/a753d978-e112-430c-9b52-79fc60afa7c1">

### Browsers

Chrome, Safari

### OS

Mac

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/commit/423466dddf549299579cf6629c23a2665f9edd3e

**Comment by polinatswet** [comment]
fixed

<img width="1413" alt="Снимок экрана 2023-06-16 в 21 51 48" src="https://github.com/Hexlet/hexlet-cv/assets/120312860/35e82b09-86ce-41e5-b6f2-9c3b86f43adb">

**Comment by usernaimandrey** [comment]
Спасибо!
