### ISSUE TITLE
Bug: Отсутствует перевод подсказки в поле Recommendations

### ISSUE THREAD

**Issue by polinatswet** [Hexlet/hexlet-cv#623]
### Summary

В англоязычной версии сайта на странице опубликованного резюме в поле Recommendations отсутствует перевод подсказки на английский язык. 
Requirements: 6.1. Сайт должен иметь 2 локали интерфейса (русский/английский).

### Reproduction steps

```bash
1. Открыть https://cv.hexlet.io/
2. Пользователь авторизован.
3. Перейти на страницу любого опубликованного резюме.
4. Найти подсказку в разделе Recommendations.
```

### Expected result

You can leave recommendations for improving the resume. The editor supports markdown.

### Actual result

Отображение текста "оставьте ваши рекомендации по улучшению резюме. Редактор поддерживает маркдаун."

<img width="1104" alt="Снимок экрана 2023-06-27 в 11 05 16" src="https://github.com/Hexlet/hexlet-cv/assets/120312860/e25643e1-f605-44cd-bb6c-9fd15aa5e1e9">

### Browsers

Firefox, Chrome, Safari

### OS

Mac

**Comment by Leenday** [comment]
c39c30fb95d01fe888fc66c41aa8f38a32acbddd

**Comment by usernaimandrey** [comment]
здесь по фиксили закрываю
