### ISSUE TITLE
Поменять очередность полей по приоритету 

### ISSUE THREAD

**Issue by Alisa-V-H** [Hexlet/hexlet-cv#626]
### Problem description

Как сейчас?

![image](https://github.com/Hexlet/hexlet-cv/assets/79241796/1390532d-239c-4b2a-8333-523a32eba76c)

### Proposed solution

Как нужно: 

1) Направление 

2) Уровень (но у 99% это джуны)

3) Город

**Comment by Leenday** [comment]
Приветствую! В Assignees никого не указано, могу ПР оформить?

**Comment by qsimpleq** [comment]
Сегодня отправлю fix

**Comment by qsimpleq** [comment]
https://github.com/Hexlet/hexlet-cv/pull/633

**Comment by usernaimandrey** [comment]
@Alisa-V-H здесь вроде все можно закрыть?

**Comment by ssssank** [comment]
Алиса дала добро на закрытие
