### ISSUE TITLE
Bug: Отсутствует перевод кнопки "Отменить" при удалении комментария к рекомендации

### ISSUE THREAD

**Issue by polinatswet** [Hexlet/hexlet-cv#628]
### Summary

В англоязычной версии сайта при удалении комментария, который оставлен в ответ на рекомендацию к резюме,
в окне с вопросом "Are you sure?" отображается кнопка без перевода - "Отменить".
Requirements: 6.1. Сайт должен иметь 2 локали интерфейса (русский/английский).

### Reproduction steps

```bash
1. Открыть https://cv.hexlet.io/
2. Пользователь авторизован.
3. Перейти на страницу опубликованного резюме, имеющего рекомендацию от другого пользователя.
4. В Recommendations заполнить поле Add a comment, и подтвердить Save.
5. Нажать кнопку удаления Х напротив опубликованного комментария к рекомендации.
6. В появившемся окне "Are you sure?" прочитать названия кнопок.
```

### Expected result

Отображается кнопка "Сancel".

### Actual result

Отображается кнопка "Отменить".

<img width="1405" alt="Снимок экрана 2023-07-04 в 13 22 06" src="https://github.com/Hexlet/hexlet-cv/assets/120312860/43793763-d976-43c7-819f-23aad3335e60">

### Browsers

Firefox, Chrome, Safari

### OS

Mac

**Comment by fey** [comment]
@polinatswet эта штука не зависит от платформы, тк вызывается тк кнопка рисуется не сайтом, а самим браузером. Т.е. текст кнопок (локаль) зависит от локали вашего браузера.

**Comment by polinatswet** [comment]
@fey в https://github.com/Hexlet/hexlet-cv/issues/630 то же самое будет?
