### ISSUE TITLE
Bug: Отсутствует перевод  заголовка "Редактирование комментария"

### ISSUE THREAD

**Issue by polinatswet** [Hexlet/hexlet-cv#629]
### Summary

Англоязычная версия сайта, раздел Recommendations.
При попытке редактирования комментария, который был оставлен в ответ на рекомендацию к резюме,
отображается текст на русском языке.
Requirements: 6.1. Сайт должен иметь 2 локали интерфейса (русский/английский).

### Reproduction steps

```bash
1. Открыть https://cv.hexlet.io/
2. Пользователь авторизован.
3. Перейти на страницу опубликованного резюме, имеющего рекомендацию.
4. В Recommendations заполнить поле Add a comment, и подтвердить Save.
5. Нажать кнопку редактирования напротив опубликованного комментария.
6. Прочитать заголовок открытой страницы.
```

### Expected result

Editing a comment

### Actual result

Отображен текст "Редактирование комментария".

<img width="1374" alt="Снимок экрана 2023-07-04 в 14 24 25" src="https://github.com/Hexlet/hexlet-cv/assets/120312860/eec484fb-bdb0-49a1-a2ab-89474f6b389b">

### Browsers

Firefox, Chrome, Safari

### OS

Mac

**Comment by Leenday** [comment]
e1ac93cc7ccd9d4c91d4eb72249d93b5b3e35ad1

**Comment by polinatswet** [comment]
fixed

<img width="1006" alt="Снимок экрана 2023-07-05 в 15 13 07" src="https://github.com/Hexlet/hexlet-cv/assets/120312860/64ceda46-91c7-4b54-962e-d38563e15514">
