### ISSUE TITLE
Bug: Отсутствует перевод у кнопки "Отмена" при удалении рекомендации

### ISSUE THREAD

**Issue by polinatswet** [Hexlet/hexlet-cv#630]
### Summary

В англоязычной версии сайта при удалении рекомендации к резюме ,
в окне с вопросом "Are you sure?" отображается кнопка без перевода - "Отменить".
Requirements: 6.1. Сайт должен иметь 2 локали интерфейса (русский/английский).

### Reproduction steps

```bash
1. Открыть https://cv.hexlet.io/
2. Авторизоваться.
3. Перейти на страницу опубликованного резюме.
4. Оставить рекомендацию к резюме.
5. Нажать кнопку удаления Х напротив опубликованной рекомендации.
6. В появившемся окне "Are you sure?" прочитать названия кнопок.
```

### Expected result

Отображается кнопка "Сancel".

### Actual result

Отображается кнопка "Отмена".

<img width="1074" alt="Снимок экрана 2023-07-04 в 15 15 34" src="https://github.com/Hexlet/hexlet-cv/assets/120312860/12b6446e-41db-4ae4-b6be-679468de353d">

### Browsers

Firefox, Chrome, Safari

### OS

Mac

**Comment by polinatswet** [comment]
https://github.com/Hexlet/hexlet-cv/issues/628#issuecomment-1620336607

**Comment by fey** [comment]
Ага, тут такая же штука. 
https://developer.mozilla.org/ru/docs/Web/API/Window/confirm
