### ISSUE TITLE
Bug: При печати резюме переход к странице 500 Internal Server Error

### ISSUE THREAD

**Issue by polinatswet** [Hexlet/hexlet-cv#634]
### Summary

В англоязычной версии сайта при попытке просмотра резюме перед печатью происходит переход на страницу 500 Internal Server Error. 
Кнопка вывода на печать существует на сайте, называется Preview PDF, но приходится пользоваться меню браузера.

### Reproduction steps

```bash
1. Открыть https://cv.hexlet.io/
2. Войти в учетную запись.
3. Открыть https://cv.hexlet.io/account/resumes
4. Перейти на страницу опубликованного резюме.
5. Нажать кнопку Preview PDF с изображением принтера.
```

### Expected result

Доступен предварительный просмотр резюме, такой же, как в русской версии.

### Actual result

Открывается страница https://cv.hexlet.io/resumes/2820/pdfs/base.pdf  
Вывод сообщения "500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong."

<img width="1417" alt="Снимок экрана 2023-07-06 в 11 11 15" src="https://github.com/Hexlet/hexlet-cv/assets/120312860/50715e4b-a8c5-4310-ae87-e84227010d71">

### Browsers

Firefox, Chrome, Safari

### OS

Mac

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/commit/05888b29e3120c7e2bd724a3e26dfa00cac2f482

**Comment by usernaimandrey** [comment]
check!)

**Comment by polinatswet** [comment]
fixed
