### ISSUE TITLE
Bug: Орфографическая ошибка в фильтре вакансий "Выберите уровень"

### ISSUE THREAD

**Issue by polinatswet** [Hexlet/hexlet-cv#640]
### Summary

При фильтрации вакансий по уровню в открытой вкладке среди вариантов отображается слово "С**и**ньор".
Правила орфографии и этимологии предполагают "С**е**ньор" , s**e**nior.

### Reproduction steps

```bash
1. Открыть https://cv.hexlet.io/ru/vacancies
2. Развернуть список фильтра "Выберите уровень".
3. Прочитать строку 5.
```

### Expected result

С**е**ньор

### Actual result

С**и**ньор

<img width="1077" alt="Снимок экрана 2023-07-07 в 19 27 30" src="https://github.com/Hexlet/hexlet-cv/assets/120312860/5eb6479d-9b07-4320-9534-2bede14fb36b">

### Browsers

Firefox, Chrome, Safari

### OS

Mac

**Comment by zhabinka** [comment]
Исправили – https://github.com/Hexlet/hexlet-cv/commit/bfddca27d617fc9fa07bf4e44d8a406752b4406b#diff-d1896f249b0e991ae9ea3b294961d1492ce2733dada78ed5f1f2d3e403c87b88L38

**Comment by polinatswet** [comment]
fixed
