### ISSUE TITLE
Bug: отсутствует валидация полей при логине

### ISSUE THREAD

**Issue by SkyAjax** [Hexlet/hexlet-cv#653]
### Summary

Форма логина позволяет отправлять на сервер пустые данные и после пользователю показывается "неправильный логин или пароль"

### Reproduction steps

```bash
1. зайти на сайт https://cv.hexlet.io/ru
2. нажать на кнопку "Войти"
3. отправить пустые поля
```

### Expected result

Кнопка отправки на пустых полях или заблокирована или при нажатии кнопки отправки поля проходят валидацию

### Actual result

![chrome_MTlGaVE7Gu](https://github.com/Hexlet/hexlet-cv/assets/45942344/daa1830f-4d7f-4e30-9556-8d2f567c0b14)

### Browsers

Chrome, Safari

### OS

Windows, Mac

**Comment by usernaimandrey** [comment]
Небольшое уточнение: валидация данных происходит не на клиенте а на сервер, так же как и рендерин страниц то же происходит на сервере(тут web 2.0 и почти нет JavaScript - а), по этому данные должны отправится на сервер что бы поройти валидацию

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/commit/6d698313cd75d8f34ec86a937e858e010fde6d97
