### ISSUE TITLE
Несоответсвие языка в карточке пользователя

### ISSUE THREAD

**Issue by Shvidunov** [Hexlet/hexlet-cv#658]
### Summary

В версии EN, при переходе к информацию о пользователе, фильтр "Карьерный трек" отображен на русском языке

### Reproduction steps

```bash
1. перейти по адресу https://cv.hexlet.io/
2. перейти к информации о пользователе кликом по имени пользователя под превью резюме
3. проверить отображение фильтров в карточке пользователя
```

### Expected result

все фильтры на английском языке

### Actual result

фильтр "Карьерный трек" отображен на русском языке

![image](https://github.com/Hexlet/hexlet-cv/assets/121935818/4433d91a-1e79-4beb-864e-2c456c2d3ad8)

### Browsers

Firefox, Chrome

### OS

Windows

**Comment by asenka0301** [comment]
Здравствуйте, возьму в работу

**Comment by qsimpleq** [comment]
Беру

**Comment by qsimpleq** [comment]
https://github.com/Hexlet/hexlet-cv/pull/669

**Comment by qsimpleq** [comment]
Можно закрывать - исправлено
