### ISSUE TITLE
Протестировать карьерный трек QA

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-cv#662]
### Problem description

Запустили карьерный трек для тестировщиков. Возможны нерабочие ссылки, какие-то баги и тд.

### Proposed solution

Надо посмотреть всё ли коректно работает, отображается. Корректны ли ссылки, всё ли открывается и т.д.

Для тестирования необходимо зарегистрироваться и скинуть ссылку на свой профиль.

**Comment by glazovanastasia** [comment]
- На стартовой странице не отображается список в маркдауне 
![image](https://github.com/Hexlet/hexlet-cv/assets/127899807/37459408-6ff5-478d-8167-735e85deec12)
- **Шаг 4** 
>"потому что только через ваш код, рекрутер или тимлид могут оценить" - запятая не нужна;

Карьерный трек для QA, но текст взят и написан так же, как и для разработчиков. Наверное, хотелось бы немного подогнанный сценарий трека именно для тестировщиков, а немного редактируя шаблон текста разрабов (конкретно с этого раздела начинается и продолжается в последующих некоторых шагах), ссылка на чек-лист корректна;
- Поломалось после нажатия на "**Завершить шаг**" 4 при переходе на 5, но вручную по шагам прощёлкивается, адрес странички меняется на step=5. Возможно, это что-то временное в моменте было
![image](https://github.com/Hexlet/hexlet-cv/assets/127899807/64e7beda-9d4a-4f14-903c-6ee514b631cd)
- **Шаг 6** 
>Что вам понадобится для прохождения тестового интервью
>1. Проработанное с карьерным консультантом Хекслета резюме. Оно у вас должно быть оформлено на Хекслет CV
>2. Проработанное с карьерным консультантом Хекслета сопроводительное письмо
>3. Оформленный профиль на GitHub (он может понадобится вашему интервьюверу)
>4. Вы завершили и сдали 2 проекта _(составить предложение в одном грамматическом стиле с предыдущими, напр. Завершенные и принятые 2 проекта)_

>"(он может понадобится вашему интервьюверу)" - поправить слово интервьюер :)

- **Шаг 7**
>"Добавьте сведения об обучении в разделе "Дополнительное образование, если хотите попасть в [список выпускников Хекслета](https://career.habr.com/education_centers/3-hekslet)" - закрыть кавычки;
- **Шаг 8**
>"привлекательным кандидатом для работодателя, а следовательно, повышает ваши шансы" - выделить вводное слово запятой _(а, следовательно,)_

>"На этом шаге, вы сможете пройти реальную" - запятая не нужна;

>"На этом шаге, вы сможете пройти реальную практику, улучшить свои знания и наполнить своё портфолио разработчика." - но ведь _тестировщика_ :)

Пока прям багов для ишью не нашла, редиректа по ссылкам нет, открываются корректные, запросы все отправляются со статусом 200

**Comment by ElenaSimanina** [comment]
Всем привет! На стартовой странице, слово пройдено написано с 2 "н", должно быть с одной, видимо опечатка
![Опечатка пройдено](https://github.com/Hexlet/hexlet-cv/assets/135851722/3dd55e30-2f08-442b-8e07-567be2f59f64)

**Comment by ElenaSimanina** [comment]
Нет страницы на ссылку из документа "Компании-партнеры" 
**(Так понимаю, что это не баг, так как  в итоге можем найти нужную информацию.  Возможно просто недоделанный функционал😊)**
Воспроизведено:  Google Chrome Версия 116.0.5845.180 (Официальная сборка), (64 бит), операционная система Windows 10
1. На стартовой странице  https://cv.hexlet.io/ru/account/members нажать ссылку [Про компании-партнёры Хекслета](https://docs.google.com/document/d/15Dhxp7fj3JKup7CO2wFNoCRTRkZWDS5bO_qD5UQcPhA/edit)
2. Перейти на страницу https://docs.google.com/  "Компании-партнеры" 
3. В Гугл Док нажать ссылку  [в этом шаге Карьерного трека на Хекслет CV](https://cv.hexlet.io/ru/admin/careers/1/steps/17).
4. Появляется сообщение:  "Ой, там пусто
Такое случается, когда страница была удалена или в адрес случайно закралась ошибка. Но ничего страшного, можно просто ткнуть на любой пункт меню сверху и попасть в нужное место."
![Нерабочая ссылка](https://github.com/Hexlet/hexlet-cv/assets/135851722/5a7b96ee-c7dc-4729-a04c-e5251a3427e9)

Прямых багов тоже пока не нашла)) Коды ответов 200)

**Comment by ElenaSimanina** [comment]
### Ссылка на  "Сайт с поиском вакансий и постингом резюме" - https://www.svyazi.app/jobs указывает на несуществующую страницу 
Воспроизведено: Google Chrome Версия 116.0.5845.180 (Официальная сборка), (64 бит), операционная система Windows 10
1. Открыть страницу 10 шаг Карьерного трека https://cv.hexlet.io/ru/careers/qa/members/272
2. На 10 шаге Карьерного трека нажать ссылку :  Список площадок вы найдёте [здесь](https://docs.google.com/document/d/1X26UtHarvYQcYTXMtteGsUjCF5HU67Z9I7El6QkIcTU/edit#heading=h.9dtwvaurt21v)!
3. Перейти на страницу https://docs.google.com/document/d/1X26UtHarvYQcYTXMtteGsUjCF5HU67Z9I7El6QkIcTU/edit "Площадки и сервисы для поиска работы"
4. Нажать на ссылку  сайта с поиском вакансий и постингом резюме https://www.svyazi.app/jobs 
5. При переходе по ссылке  появляется сообщение : "Не удается получить доступ к сайту"

![Нерабочая ссылка на сайт](https://github.com/Hexlet/hexlet-cv/assets/135851722/af45fdd7-e6df-415b-b7d5-a53ff8d7a291)
![Сообщение о недоступности сайта](https://github.com/Hexlet/hexlet-cv/assets/135851722/97c4f47b-d14e-43f1-a9e0-63b4b6f52465)

**Comment by Alisa-V-H** [comment]
Fixed.

**Comment by AnnaGurina** [comment]
### Актуальные проблемы из предыдущих отчетов (с дополнениями):

1.	На стартовой странице не отображается список в маркдауне

**Дополнение**   _Должно быть так_:
Больше о Карьерном треке
•	[Про компании-партнёры Хекслета](https://docs.google.com/document/d/15Dhxp7fj3JKup7CO2wFNoCRTRkZWDS5bO_qD5UQcPhA/edit)
•	[Handbook: Q&A](https://docs.google.com/document/d/11hfuklINOLu1myYi1th7uMwyVHaLDoepBX__gI0sTbY/edit#heading=h.f09nn6gse1ao). Здесь собраны ответы на самые часто задаваемые вопросы
**Дополнение** _следует добавить двоеточие после «больше о карьерном треке»_

2.	Шаг 6
**Дополнение** вы будете в большей степени уверены и подготовлены к выходу на рынок IT и поиску работы. –   _либо исправить на «уверены в себе» либо на «уверенны»_ 
Что вам понадобится для прохождения тестового интервью **Дополнение** _не хватает двоеточия_
1.	Проработанное с карьерным консультантом Хекслета резюме. Оно у вас должно быть оформлено на Хекслет CV
2.	Проработанное с карьерным консультантом Хекслета сопроводительное письмо
3.	Оформленный профиль на GitHub (он может понадобится вашему интервьюверу) _- поправить слово интервьюер_
4.	Вы завершили и сдали 2 проекта _- составить предложение в одном грамматическом стиле с предыдущими, напр. Завершенные и принятые 2 проекта_

3.	Шаг 7
Добавьте сведения об обучении в разделе "Дополнительное образование, если хотите попасть в [список выпускников Хекслета](https://career.habr.com/education_centers/3-hekslet)   _- закрыть кавычки_

4.	Шаг 8
"привлекательным кандидатом для работодателя, а следовательно, повышает ваши шансы" - _выделить вводное слово запятой (а, следовательно,)_ **Дополнение** _не соглашусь с добавлением запятой перед вводным словом «следовательно». Запятая была бы нужна, если бы при удалении вводного слова из предложения смысл не изменился, но в данном случае это невозможно, значит запятая после «а» не нужна – ошибки нет._
"На этом шаге, вы сможете пройти реальную" _- запятая не нужна;_
"На этом шаге, вы сможете пройти реальную практику, улучшить свои знания и наполнить своё портфолио разработчика." – _заменить «разработчика» на «тестировщика»_ **Дополнение**   _и запятая после «на этом шаге» не нужна_
**Дополнение**  перейти к практике, а именно, к наработке портфолио. – _запятая после «именно» не нужна_

5.	 _Нет страницы на ссылку из документа "Компании-партнеры"_
- На стартовой странице https://cv.hexlet.io/ru/account/members нажать ссылку [Про компании-партнёры Хекслета](https://docs.google.com/document/d/15Dhxp7fj3JKup7CO2wFNoCRTRkZWDS5bO_qD5UQcPhA/edit)
- Перейти на страницу https://docs.google.com/ "Компании-партнеры"
- В Гугл Док нажать ссылку [в этом шаге Карьерного трека на Хекслет CV](https://cv.hexlet.io/ru/admin/careers/1/steps/17).
- Появляется сообщение: "Ой, там пусто

### Новое:

1.	Стартовая страница https://cv.hexlet.io/ru/account/members Раздел «Пройденные»:
Если вы еще не являетесь участником карьерного трека, узнайте что такое [карьерный трек](https://cv.hexlet.io/ru/employment) и как к нему присоединится.
_Необходима запятая после «узнайте». Также «присоединится» исправить на «присоединиться»_

2.	_Редактировать чек-листы и другие документы:
а) В текстах (как на сайте, так и в документах по ссылкам) много опечаток, грамматических и пунктуационных ошибок. В текстах на сайте почти все ошибки мы с коллегами указали, но на ошибках в документах останавливаться подробно не хочется, их немало. Поэтому рекомендация – прогнать ВСЕ документы через редактор, исправить все ошибки. 
б) Чек-листы необходимо привести к единому формату – doc., раз подразумевается, что их нужно пользователю редактировать, что-то отмечать (сейчас половина в пдф), а также привести их названия к единому стилю (сейчас вразнобой). Совсем в идеале еще и пронумеровать для удобства хранения. 
в) Подразумевается, что чек-лист создан для быстрой проверки своей подготовки. Он не должен быть очень длинным. Следует сделать листы более компактными (они занимают слишком много страниц сейчас), а также поправить отступы, форматирование, шрифты (бросается в глаза)._

3.	Шаг 9 https://cv.hexlet.io/ru/careers/qa/members/257?step=9 

что вы, действительно, хотите развиваться как программист – _в данном случае «действительно» не должно выделяться запятыми_

4.	Щаг 10 https://cv.hexlet.io/ru/careers/qa/members/257?step=10 
Если вы хотите попасть в базу выпускников Хекслета, изучите шаги ниже.
Задачи:
•	Вы полностью завершили профессию в Хекслете…
_Слово «задачи» не подходит по смыслу, следует заменить на «Условия»_

5.	Шаг 11 https://cv.hexlet.io/ru/careers/qa/members/257?step=11 
Если вы завершили профессию на Хекслете и прошли практику в Open Source Начинайте откликаться на вакансии! – _нужна запятая после «source» и «начинайте» с маленькой буквы_

**Comment by Lexus111** [comment]
🔧Проверка прошла успешно. Все ссылки рабочие, но предлагаю некоторые изменения:
1. Изменить надпись "опенсоурс" на "open source" @fey
