### ISSUE TITLE
Протестировать карьерный трек для дата аналитиков

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-cv#663]
### Problem description

Запустили карьерный трек для аналитиков. Возможны нерабочие ссылки, какие-то баги и тд.

### Proposed solution

Надо посмотреть всё ли коректно работает, отображается. Корректны ли ссылки, всё ли открывается и т.д.

Для тестирования необходимо зарегистрироваться и скинуть ссылку на свой профиль.

**Comment by AnnaGurina** [comment]
1.	***Стартовая страница https://cv.hexlet.io/ru/account/members
а) Раздел «Пройденные»
Если вы еще не являетесь участником карьерного трека, узнайте что такое [карьерный трек](https://cv.hexlet.io/ru/employment) и как к нему присоединится.
_Необходима запятая после «узнайте». Также «присоединится» исправить на «присоединиться»_
б) [Handbook: Q&A](https://docs.google.com/document/d/11hfuklINOLu1myYi1th7uMwyVHaLDoepBX__gI0sTbY/edit#heading=h.f09nn6gse1ao). Здесь собраны ответы на самые часто задаваемые вопросы. Здесь собраны ответы на самые часто задаваемые вопросы
_Убрать повтор фразы_
в) _Нет страницы на ссылку из документа "Компании-партнеры":_
Стартовая - [Про компании-партнёры Хекслета](https://docs.google.com/document/d/15Dhxp7fj3JKup7CO2wFNoCRTRkZWDS5bO_qD5UQcPhA/edit) – в Гугл-доке нажать [в этом шаге Карьерного трека на Хекслет CV](https://cv.hexlet.io/ru/admin/careers/1/steps/17) – появляется сообщение «Oops, it's empty»
2.	***_Редактировать чек-листы и другие документы:
а) В текстах (как на сайте, так и в документах по ссылкам) много опечаток, грамматических и пунктуационных ошибок. В текстах на сайте почти все ошибки мы с коллегами указали, но на ошибках в документах останавливаться подробно не хочется, их немало. Поэтому рекомендация – прогнать ВСЕ документы через редактор, исправить все ошибки.
б) Чек-листы необходимо привести к единому формату – doc., раз подразумевается, что их нужно пользователю редактировать, что-то отмечать (сейчас половина в пдф), а также привести их названия к единому стилю (сейчас вразнобой). Совсем в идеале еще и пронумеровать для удобства хранения. В некоторых названиях присутствует «QA»
в) Подразумевается, что чек-лист создан для быстрой проверки своей подготовки. Он не должен быть очень длинным. Следует сделать листы более компактными (они занимают слишком много страниц сейчас), а также поправить отступы, форматирование, шрифты (бросается в глаза)._
3.	_Порядок шагов, начиная с шага 6.
Шаги пронумерованы в другом порядке, нежели в КТ для QA. Судя по всему, 6ым шагом в КТ для тест идет тестовое интервью, потому что до этого пройден минимум, необходимый для тестового. А в КТ для аналит тестовое интервью идет в конце (видимо) по логике, что сначала все портфолио целиком, а потом уже собеседование. Я не знаю, насколько это принципиально для пользователей, мне кажется нет большой разницы, а для внутренней работы наверно было бы удобно иметь единый порядок шагов во всех КТ. Выполнение доп заданий тоже в другом порядке._
4.	***Шаг 6
Добавьте сведения об обучении в разделе "Дополнительное образование, если хотите попасть в [список выпускников Хекслета](https://career.habr.com/education_centers/3-hekslet) - _закрыть кавычки_
5.	***Шаг 7
"На этом шаге, вы сможете пройти реальную" - _запятая не нужна;_
"На этом шаге, вы сможете пройти реальную практику, улучшить свои знания и наполнить своё портфолио разработчика." – _заменить «разработчика» на «аналитика», но еще лучше – заменить на любое нейтральное слово, например «специалиста», чтобы не править каждый КТ в отдельности И запятая после «на этом шаге» не нужна_
перейти к практике, а именно, к наработке портфолио. – _запятая после «именно» не нужна_
6.	***Шаг 8
вы будете в большей степени уверены и подготовлены к выходу на рынок IT и поиску работы. _– либо исправить на «уверены в себе» либо на «уверенны»_
Что вам понадобится для прохождения тестового интервью - _не хватает двоеточия_
Оформленный профиль на GitHub (он может понадобится вашему интервьюверу) - _поправить слово интервьюер_
Вы завершили и сдали 2 проекта - _составить предложение в одном грамматическом стиле с предыдущими, напр. Завершенные и принятые 2 проекта_
7.	***Шаг 9  
что вы, действительно, хотите развиваться как программист – _в данном случае «действительно» не должно выделяться запятыми_
8.	***Шаг 10  
Если вы завершили профессию на Хекслете и прошли практику в Open Source Начинайте откликаться на вакансии! – _нужна запятая после «source» и «начинайте» с маленькой буквы_
9.	***Шаг 11  
Если вы хотите попасть в базу выпускников Хекслета, изучите шаги ниже.
Задачи:
• Вы полностью завершили профессию в Хекслете…
_Слово «задачи» не подходит по смыслу, следует заменить на «Условия»_
