### ISSUE TITLE
Добавить выгрузку в CSV резюме

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-cv#664]
### Problem description

Выгрузка резюме полезна для анализа данных, сбора статистики и тд

### Proposed solution

В админке. на странице резюме сделать выгрузку в CSV, с полями

* id
* name
* state
* user (full_name)
* email
* дата создания
![image](https://github.com/Hexlet/hexlet-cv/assets/697178/e343da30-ca29-4c20-bd6e-642305c29c6b)

**Comment by amd-9** [comment]
@fey имеется ввиду выгрузка содержимого всей таблицы в CSV?

**Comment by amd-9** [comment]
Закинул PR  с реализацией по аналогии с разделом вакансий в админке.

**Comment by fey** [comment]
@amd-9 отлично!
