### ISSUE TITLE
Bug: При выводе резюме в pdf перед ссылками исчезает пробел

### ISSUE THREAD

**Issue by bazilval** [Hexlet/hexlet-cv#671]
### Summary

При выводе резюме в pdf перед ссылками исчезает пробел
![image](https://github.com/Hexlet/hexlet-cv/assets/29205112/8ef87526-a07a-4da5-a825-9dec22ffba77)

### Reproduction steps

```bash
1. Откройте свои резюме
2. Нажмите "Вывести в pdf"
```

### Expected result

Текст резюме с пробелами перед ссылками

### Actual result

Отсутствие пробелов перед ссылками

**Comment by amd-9** [comment]
@fey проверил у себя локально. Указанных прогбем в выгрузки не нашел. Нужно больше конкретики по багу

**Comment by fey** [comment]
@bazilval можете чекнуть еще раз?)
