### ISSUE TITLE
Bug: После добавления меня в Карьерный трек, раннее созданное резюме пропало из списка "Мои резюме"

### ISSUE THREAD

**Issue by bazilval** [Hexlet/hexlet-cv#673]
### Summary

После добавления меня в Карьерный трек, раннее созданное резюме пропало из списка "Мои резюме". При чём если открыть уведомления и перейти по уведомлению о том, что AI-помощник дал комментарий вашему резюме, то резюме открывается. Но самого комментария уже нет

### Reproduction steps

```bash
1. Создайте резюме
2. Присоединитесь к Карьерному треку
3. Откройте список "Мои резюме"
```

### Expected result

Наличие ранее созданного резюме

### Actual result

Ранее созданное резюме отсутствует

### Browsers

Microsoft Edge

### OS

Windows

**Comment by bazilval** [comment]
Обнаружил, что резюме сделанные на английском отражаются, только если язык выставлен английский

**Comment by usernaimandrey** [comment]
Все верно, английская версия сайта и русская это можно сказать два разных сайта, выборки из БД идут в соответствии с локалью, так что если вы создали резюме в en локали в русской его не будет - это не баг, это фича
