### ISSUE TITLE
Добавить страницу с вакансиями на модерации

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-cv#674]
### Problem description

Карьерному консультанту нужен удобный интерфейс для работы с вакансиями

### Proposed solution

Добавляем в админке раздел "Вакансии", где будет два пункта
* На модерации - открывает страницу https://cv.hexlet.io/ru/admin/vacancies + фильтр "состояние - на модерации".
* Все вакансии

![image](https://github.com/Hexlet/hexlet-cv/assets/697178/bd77ca5b-9b6c-4977-a8f0-6d42386011fb)

**Comment by qsimpleq** [comment]
Беру

**Comment by qsimpleq** [comment]
https://github.com/Hexlet/hexlet-cv/pull/677#issuecomment-1726058276
