### ISSUE TITLE
Редирект после обновления вакансии в админке

### ISSUE THREAD

**Issue by usernaimandrey** [Hexlet/hexlet-cv#675]
### Problem description

сейчас после обновления вакансии в админке происходит редирект на первую страницу - это довольно не удобно, если ты редактируешь вакансию на 5 стр. обновляешь ее и тебя редиректит на первую, приходится идти обратно на пятую
https://github.com/Hexlet/hexlet-cv/blob/main/app/controllers/web/admin/vacancies_controller.rb#L60

### Proposed solution

сделать редирект после обновления на редактирование, то есть после обновление вакансии редирект на форму редактирования но уже с обновленными полями

**Comment by qsimpleq** [comment]
Беру

**Comment by qsimpleq** [comment]
https://github.com/Hexlet/hexlet-cv/pull/676
