### ISSUE TITLE
Bug: Отсутствие возможности удаления рекомендации владельцем резюме

### ISSUE THREAD

**Issue by vaysl7599** [Hexlet/hexlet-cv#680]
### Summary

Нет кнопки, которой можно удалить чужую рекомендацию к своему резюме

### Reproduction steps

```bash
1. Авторизироваться в своем аккаунте.
2. Открыть резюме, на котором была оставлена рекомендация.
```

### Expected result

Отображена кнопка для удаления рекомендации

### Actual result

Отсутствует кнопка для удаления рекомендации
<img width="1034" alt="image" src="https://github.com/Hexlet/hexlet-cv/assets/122399471/366bdcdb-15ec-46d1-80a5-7633aac010ed">

### Browsers

Firefox, Chrome, Safari

### OS

Mac

**Comment by usernaimandrey** [comment]
Это не баг, это фича, чужую рекомендацию может нельзя удалять, ее может удалить только автор рекомендации

**Comment by usernaimandrey** [comment]
Тут возможно стоит перефразировать: дать возможность админам удалять рекомендации, ну на случай если там есть оскорбления или не цензурщина

**Comment by fey** [comment]
Да, обычный пользователь не может удалять рекомендации в своих резюме.  Это может делать админ или автор рекоменадции. Можете это внести в требования проекта.

Составлю отдельный ищщус на модерацию рекомендаций.
