### ISSUE TITLE
Разграничить контент во всех разделах на Хекслет CV по локалям: Eng & Rus

### ISSUE THREAD

**Issue by Alisa-V-H** [Hexlet/hexlet-cv#683]
### Problem description

На данный момент информация в обеих локалях смешанная, то есть в Rus локали я вижу вакансии и Карьерный трек и на русском, и на английском, соответственно, в локали Eng происходит то же самое. С этим неудобно работать, потому что, когда всё в одной куче - это отвлекает, да и вообще, не по уму. 

### Proposed solution

Разграничить: то, что на Hexlet CV ENG - только на английском (Карьерный трек, вакансии, резюме, админка, контент), а на локали RUS - только всё по-русски. 
Локаль RUS:
![image](https://github.com/Hexlet/hexlet-cv/assets/79241796/20f61bcc-e946-4a41-ac61-920b7882e653)
Локаль ENG:
![image](https://github.com/Hexlet/hexlet-cv/assets/79241796/17ecfba5-8d2c-48ee-8fcc-7bcdfa229e98)

**Comment by fey** [comment]
Если при выполнении задачки будут вопросы - спрашивайте вопросы сюда.

**Comment by usernaimandrey** [comment]
Небольшое уточнение: Для пользователей контент уже разделен по локалям(за исключением карьерного трека - это тоже нужно сделать, что бы в профиле пользователя его КТ выводились в соответствии с локалью), разделить надо для админки

**Comment by qsimpleq** [comment]
Беру

**Comment by fey** [comment]
@qsimpleq привет. Как успехи? Можете создать draft-пулл реквест и в нем будем видеть изменения.

**Comment by fey** [comment]
@qsimpleq успеем сделать до середины след недели? Если нет уверенности. то можно задачку дать Андрею Ш и взять другую задачку ;)

**Comment by qsimpleq** [comment]
Передаю тогда
