### ISSUE TITLE
Смена статуса вакансии в один клик 

### ISSUE THREAD

**Issue by Alisa-V-H** [Hexlet/hexlet-cv#684]
### Problem description

Понять актуальна ли вакансия для Хекслета, можно сразу по её названию. Например, мы не обучаем ML, следовательно, такую вакансию можно сразу убирать в архив без того, чтобы лезть в её внутрянку. Однако, сейчас такой возможности нет, что добавляет ненужную рукопашку в работе. 
![image](https://github.com/Hexlet/hexlet-cv/assets/79241796/564079e1-eb6b-4160-86c8-e2fd1cc2aa65)
![image](https://github.com/Hexlet/hexlet-cv/assets/79241796/ae6451b6-448a-4be3-afdd-2a9640f12fae)

### Proposed solution

Чтобы в один клик убирать неактуальные для Хекслет вакансии в архив, прикрутить кнопку, при клике на которую, вакансия будет сразу улетать в архив, без того, чтобы заходить во внутрь этой вакансии. 
Кнопка может быть здесь:
![image](https://github.com/Hexlet/hexlet-cv/assets/79241796/eca8055d-4469-49ae-a081-e3ebad0af730)

**Comment by fey** [comment]
При выполнении не забудьте добавить алерт с подтверждением действий и флеш сообщение.

**Comment by amd-9** [comment]
@fey какую иконку предполагается использовать по кнопку?

**Comment by amd-9** [comment]
Добавил PR. Функционал реализовал по аналогии с резюме в админке

**Comment by fey** [comment]
@Alisa-V-H принимай задачу.

**Comment by Alisa-V-H** [comment]
Вроде работает.
