### ISSUE TITLE
Bug: Обновленное резюме не поднимается в списке на главной странице сайта

### ISSUE THREAD

**Issue by alexidude** [Hexlet/hexlet-cv#693]
### Summary

Обновленное резюме не поднимается в списке на главной странице сайта

### Reproduction steps

```bash
1. Перейти на страницу "Мои резюме"
2. Нажать кнопку редактирования резюме
3. Внести изменения в резюме
4. Нажать кнопку опубликовать резюме
5. Перейти на главную страницу
```

### Expected result

Резюме должно подняться в списке, время публикации должно обновиться

### Actual result

Резюме не поднялось, время публикации не изменилось

### Browsers

Chrome

### OS

Windows

**Comment by fey** [comment]
Добрый день. Сортировка резюме происходит по дате создания. не по дате обновления. Это можно зафиксировать в требованиях (в тест кейсах, вики проекта, в доке).
