### ISSUE TITLE
Сделать обязательным Имя и фамилию для всех пользователей

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-cv#695]
### Problem description

Сейчас у нас есть анонимные пользователи, которые могут попасть в КТ, Это неудобно для менеджера КТ, который добавляет студентов в него или следить за его активностью. 

### Proposed solution

Сделаем Имя и Фамилию обязательным для всех

Для регистрации через веб-форму добавим поля
* Имя
* Фамилия
Для входа через Github и через форму просим заполнить Имя и Фамилию на странице настроек https://cv.hexlet.io/ru/account/profile/edit

Если у пользователя ФИО не заполнены - выводим ему флеш с просьбой заполнить поля.

Т.е. логика - если вошел в систему и у тебя нет фио - тебе открывается страница с настройками и флешкой "заполни фио", если уже залогинен, то выводится флеш "заполни _тут_ фио"

**Comment by fey** [comment]
https://github.com/Hexlet/hexlet-cv/commit/94e04c6d9bfdee2f8aa5087101b95a3b2470b4e2

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/commit/84afbb929098a18561cd5f1d67f229ab88c760cc

https://github.com/Hexlet/hexlet-cv/commit/a3d3a7d9264de8946c489dac78e43023adaca835

https://github.com/Hexlet/hexlet-cv/commit/3619f0418adcb630211f471e120ebdc287100fd2

https://github.com/Hexlet/hexlet-cv/commit/f390f190ab1aa6088724c6968d5011fe8bc888cb

**Comment by Mimicry56** [comment]
Проверено. Поля Имя и Фамилия работают как обязательные при регистрации и при входе через Github просит заполнить поля Имя и Фамилия на странице настроек.

Валидация полей запрещает "пустые символы", но пропускает спецсимволы и цифры, длина полей более 40 символов.

**Comment by usernaimandrey** [comment]
Валидацию на длину имени и фамилии добавил https://github.com/Hexlet/hexlet-cv/commit/c9a7cd1c7ac54e070e35811cf964ee765ce65fe1
