### ISSUE TITLE
Поменять шаблон резюме на Хекслет CV

### ISSUE THREAD

**Issue by Alisa-V-H** [Hexlet/hexlet-cv#696]
### Problem description

На данный момент шаблон по резюме, который заполняют пользователи на Хекслет CV - не корректен, так как в нём не соблюдена структура, которую бы пропускали ATS, и которая была бы понятна рекрутерам. Есть устоявшейся шаблон, который используется, как на рынке РФ и СНГ, так и за рубежом. 
По шаблону проговорили с Product Owner, он был введён давно, и тогда не знали ничего по правильной структуре резюме. 

### Proposed solution

Переделать шаблон резюме на Хекслет CV. По сути, нужно поменять структуру полей: какие поля убрать совсем, а какие-то просто переставить. 
Пример шаблона: https://docs.google.com/document/d/1kykXWg_g9Fu0T_qUcLodjyPv-cplHSo7pIaKVYq8ChA/edit 
Пример заполненного шаблона: https://docs.google.com/document/d/1ENdAY1wD5Z1B7CprMD9FX_FYvzlk0FWpLZzXyvfXt2c/edit
Пометки по полям на Хекслет CV: https://docs.google.com/document/d/139BJp-51V-clFcwjHM_3B5RkqJFuu_WN/edit

**Comment by bobrov-site** [comment]
Откройте пожалуйста доступ к ссылкам. Потому что без доступа невозможно прочитать

**Comment by fey** [comment]
По задаче - 
Можно разделить на две части. Первая - это верстка с созданием требуемого шаблона
Вторая - добавление отсутствющих полей. попробуйте начать с визуальной части и если чего-то не будет хватать - сообщите.

**Comment by fey** [comment]
@Alisa-V-H @usernaimandrey вижу, что у нас сейчас новый шаблон. Что-то еще нужно тут делать?

**Comment by usernaimandrey** [comment]
Да вроде все сдесь
