### ISSUE TITLE
Вывести количество студентов для админов КТ

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-cv#700]
### Problem description

Менеджеру КТ тяжело вручную считать количество студентов на каждом этапе.

Необходимо вывести это количество, чтобы облегчить жизнь.

### Proposed solution

На каждую вкладку выводим не только данные в таблице, но и количество студентов без учета пагинации.

Т.е. для отображения количества учитываются фильтры. А пагинация - нет.

Такой счетчик нужно вывести на 

* Списке
* Закончившие карьерный трек
* Архив
* Давно не учились.

![image](https://github.com/Hexlet/hexlet-cv/assets/697178/1b91adfd-50b0-4f06-95f3-31444396ceef)

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/commit/d27833d4cd4681527a6ef82b78d5f0d74ddd3050

**Comment by usernaimandrey** [comment]
![image](https://github.com/Hexlet/hexlet-cv/assets/48034349/6e33c1f2-4b55-4ca6-923f-656cff78b10d)
![image](https://github.com/Hexlet/hexlet-cv/assets/48034349/59f382b7-4985-4f73-894f-775cf50e7ceb)
![image](https://github.com/Hexlet/hexlet-cv/assets/48034349/4239468e-fa48-4fdc-a08a-49b7a7fb0017)
![image](https://github.com/Hexlet/hexlet-cv/assets/48034349/3e2eaee1-7f46-4d08-85fe-65e4d4f3b7de)
