### ISSUE TITLE
изменить отображение полей в разделе Карьерный трек -> студенты

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-cv#702]
### Problem description

Чтобы отлегчить жизнь карьерного менеджера по анализу данных, надо добавить некоторые поля, а некоторые поменять местами

> по каждому состоянию не отображается дата. Я не вижу, с какой даты студент в архиве; с какой даты студент не активен. Везде проставляется дата старта КТ — этого мало для полноценного анализа

### Proposed solution

Раздел в Архиве
https://cv.hexlet.io/ru/admin/career_member_users/archived
Добавить дату "Отправлен в архив" - дата отправки студента в архив

На всех страницах добавить дату Последней активности

**Comment by usernaimandrey** [comment]
![image](https://github.com/Hexlet/hexlet-cv/assets/48034349/aa7b5be1-ec52-46dc-a38a-6b7edfb67e93)
