### ISSUE TITLE
Bug: Дублирование данный из поля "Телеграм" в поле "Дополнительные контакты"

### ISSUE THREAD

**Issue by DmGorokhov** [Hexlet/hexlet-cv#718]
### Summary

вбиваю ссылку на LinkedIn в поле дополнительных контактов
![image](https://github.com/Hexlet/hexlet-cv/assets/117211516/3291fdc7-b8a6-4a83-8fc1-d1d5c2f2a651)
при сохранение и выводе резюме просто дублируется телеграм
![image](https://github.com/Hexlet/hexlet-cv/assets/117211516/2843dd97-985e-46bd-b107-342eaa7352b6)

Также, думаю, имеет смысл сделать эти ссылки кликабельными

### Reproduction steps

```bash
Создаем резюме, заполняем поле "Дополнительные контакты" и "Телеграм"
```

### Expected result

Ожидаем, что будут свои данные в каждом поле после публикации

### Actual result

Данные поля телеграм просто копируются в поле "дополнитетльны контакты". Если телеграмм не вводить, то поле "дополнительные контакты" также будет пустым. При этом в базе сохранение идет, тк после входа в режим редактирования вся информация верная. Видимо на рендеренге где-то дублируется поле

### Browsers

Chrome

### OS

Linux

**Comment by usernaimandrey** [comment]
fixed
