### ISSUE TITLE
Bug: Опечатка

### ISSUE THREAD

**Issue by Karamysh** [Hexlet/hexlet-cv#739]
### Summary

Опечатка в слове "Примите" 

![image](https://github.com/Hexlet/hexlet-cv/assets/28097002/ab18c78f-3a5c-4b45-a17b-5e2d12803627)

### Reproduction steps

```bash
1. Карьерный трек для тестировщиков
2. Шаг 12
3. Пункт 4
```

### Expected result

Примите

### Actual result

Примети

### Browsers

Chrome

### OS

Windows

**Comment by fey** [comment]
@Karamysh Пишут, что поправили. Можете проверить?

**Comment by Karamysh** [comment]
@fey Да, всё хорошо
