### ISSUE TITLE
Feature request: Добавить возможность отправлять на модерацию вакансию

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-cv#745]
### Problem description

Сейчас пользователь, который создает вакансию, создает ее в черновике. У Карьерного консультанта нет возможности различить готовые к публикации вакансии и те, что еще не дописаны.

### Proposed solution

Добавить возможность отправлять вакансию. Предварительно обсуждали что можно сделать через селект, но решили по другому.

**Comment by fey** [comment]
Пока задача у разработчиков Хекслета.

**Comment by usernaimandrey** [comment]
Привет хотел уточнить:
> Сейчас пользователь, который создает вакансию, создает ее в черновике.

Вакансия при создании автоматом уходит на модерацию, а нужно наверное что бы уходила в черновик

**Comment by fey** [comment]
@usernaimandrey непонятно :thinking: 
сейчас все вакансии уходят в черновик

**Comment by usernaimandrey** [comment]
Да нет я проверил присоздании вакансия автоматом уходит на модерацию и в админе отображается здесь
 
<img width="1434" alt="Снимок экрана 2024-05-23 в 10 07 53" src="https://github.com/Hexlet/hexlet-cv/assets/48034349/c6ec4c41-cb01-4065-b243-4efeb6dc14bc">

**Comment by amshkv** [comment]
интересная ситуация, а мы што тогда делаем?

**Comment by fey** [comment]
Только что проверил на проде, вакансия создалась как черновик, на модерации ее нет
![image](https://github.com/Hexlet/hexlet-cv/assets/697178/eebbb4cf-7ae5-4df1-ba03-3caba0354c40)

![image](https://github.com/Hexlet/hexlet-cv/assets/697178/8a9ec64a-ab7f-4fe0-a5b5-79947f81a3dc)
![image](https://github.com/Hexlet/hexlet-cv/assets/697178/ecd86629-a5b5-4345-9ac2-d648dfdb75b0)

**Comment by amshkv** [comment]
возможно Андрей Ш создает вакансию в интерфейсе админа? ;)

**Comment by amshkv** [comment]
хотя вроде одинаковая функциональность

**Comment by amshkv** [comment]
я может что-то не догоняю, но по коду нигде нет перехода ВАКАНСИЙ в стейт на модерации

**Comment by amshkv** [comment]
ну и на скрине Андрея Ш это запись из фикстуры

**Comment by usernaimandrey** [comment]
Да пардоньте не туда посмотрел, в черновик)

**Comment by fey** [comment]
@usernaimandrey возьмешь задачу? А то отклонение вакансии есть, а отправки на модерацию пользователем - нет.

**Comment by usernaimandrey** [comment]
Возьму

**Comment by fey** [comment]
@usernaimandrey can you continue work of Arseniy? -)
