### ISSUE TITLE
Некорректное отображение заголовка

### ISSUE THREAD

**Issue by Yawerica** [Hexlet/hexlet-cv#751]
### Summary

Фраза **### Вакансии для разработчиков** отображаются в заголовке при любом выбранном направлении

### Reproduction steps

```bash
1.В разделе Вакансии выбрать направление
2.Кликнуть на кнопку найти
3.Обратить внимание на заголовок
```

### Expected result

Если ищу вакансию для верстальщика, то заголовок должен быть###  **Вакансии для верстальщиков**

### Actual result

![слово разработчиков сохраняется](https://github.com/Hexlet/hexlet-cv/assets/148934630/58a3589d-0430-42e8-b7b8-2929bc4fe77f)

### Browsers

Chrome

### OS

Windows

**Comment by owlscatcher** [comment]
Готово #770

![image](https://github.com/user-attachments/assets/7e5064e2-c5e5-45ce-a8c7-11bf9530bdfa)
![image](https://github.com/user-attachments/assets/774829fe-adf7-41b3-ba1e-a96f410a983c)
![image](https://github.com/user-attachments/assets/37711c68-4094-4339-a030-bddc3159166b)
![image](https://github.com/user-attachments/assets/16b3b09e-f56e-45f7-a6ad-06fa217af12c)

**Comment by Yawerica** [comment]
тут проблема в том, что слово Разработчиков не для каждого поиска подходит) 

![image](https://github.com/user-attachments/assets/c591699f-4a5a-4d13-87c8-a735f965a5a6)

**Comment by owlscatcher** [comment]
> тут проблема в том, что слово Разработчиков не для каждого поиска подходит) 
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/c591699f-4a5a-4d13-87c8-a735f965a5a6)
> 
> 
> 
> 

Да, я понимаю, потому и изменил формулировку. Но этого скорее всего делать не стоит, мейнтейнеры примут решение принимать мой пр или нет. =)

**Comment by Yawerica** [comment]
@fey мб просто убрать слово "Разработчиков" из кода?))

**Comment by owlscatcher** [comment]
> @fey мб просто убрать слово "Разработчиков" из кода?))

Я примерно это и сделал, вот, можете ознакомиться с изменениями в pr: https://github.com/Hexlet/hexlet-cv/pull/770

**Comment by fey** [comment]
![image](https://github.com/user-attachments/assets/62d0128e-053a-4f33-a94d-f6f4618c3502)

**Comment by fey** [comment]
Ответ SEO:

```
Еще вариант шаблона:

H1: Вакансии по запросу:  %{position_level} %{direction} в %{city_description}

Title: Вакансии по запросу:  %{position_level} %{direction} в %{city_description} — Hexlet CV

Description: %{Количество_ваканчий} jткрытых вакансии на работу%{position_level} %{direction} в %{city_description} ✉ Уровень зарплаты до %{Максимальная_ЗП}. руб ➔ Лучшие предложения на cv.hexlet.io✔
```
@owlscatcher посмотрите, пожалуйста.

**Comment by owlscatcher** [comment]
> Ответ SEO:
> 
> ```
> Еще вариант шаблона:
> 
> H1: Вакансии по запросу:  %{position_level} %{direction} в %{city_description}
> 
> Title: Вакансии по запросу:  %{position_level} %{direction} в %{city_description} — Hexlet CV
> 
> Description: %{Количество_ваканчий} jткрытых вакансии на работу%{position_level} %{direction} в %{city_description} ✉ Уровень зарплаты до %{Максимальная_ЗП}. руб ➔ Лучшие предложения на cv.hexlet.io✔
> ```
> 
> @owlscatcher посмотрите, пожалуйста.

Примерно вот так?

![image](https://github.com/user-attachments/assets/54fec536-f5ee-4b3a-a5e7-a93493f577cd)

**Comment by owlscatcher** [comment]
> @owlscatcher а скопируйте из html теги просто (мета, тайтл, х1)
Ага, вот для `city-moskwa_direction-android_level-junior` :

```html
<meta name="description" content="1 открытых вакансий на работу Джуниор android в городе Москва. Работа для Джуниор, подборка от редакции Hexlet CV">
```

```html
<title>Вакансии по запросу: Джуниор android в городе Москва | Hexlet CV</title>
```

```html
<h1 class="mb-5">Вакансии по запросу: Джуниор android в городе Москва</h1>
```

**Comment by fey** [comment]
@owlscatcher выглядит норм)

**Comment by owlscatcher** [comment]
> @owlscatcher выглядит норм)

Обновил [PR](https://github.com/Hexlet/hexlet-cv/pull/770)
