### ISSUE TITLE
Кнопка смены пароля выглядит как текст

### ISSUE THREAD

**Issue by Yawerica** [Hexlet/hexlet-cv#755]
### Summary

Кнопка не выделяется, не имеет фона
Не очевидно что нужно нажать на неё

### Reproduction steps

```bash
precondition:
1. Иметь аккаунт на сайте Hexlet.CV

steps:
1. Перейти на страницу авторизации https://cv.hexlet.io/ru/users/sign_in
2. Кликнуть по кнопке Забыли пароль
3. Ввести email. Нажать на кнопку Выслать новый пароль
4. Перейти по ссылке, которая пришла на почту
```

### Expected result

1.предлагаю оформить кнопку как и остальные кнопки на сайте

![пожелание к виду кнопки](https://github.com/Hexlet/hexlet-cv/assets/148934630/6214a23d-9213-48f1-ae74-e95d09db425e)

### Actual result

![кнопка сменить пароль не видна](https://github.com/Hexlet/hexlet-cv/assets/148934630/6cb3c0ba-a7a0-4892-a571-39c4975de09f)

### Browsers

Chrome

### OS

Windows

**Comment by fey** [comment]
@polina-belyakaeva Be careful here, Hexlet-CV does not have a dedicated SPA, so changes may need to be made to the templates on slim

**Comment by polina-belyakaeva** [comment]
@fey thank you! I'll will pay attention to this

**Comment by fey** [comment]
@Yawerica fix deployed, pls review changes

**Comment by Yawerica** [comment]
![image](https://github.com/user-attachments/assets/416cb177-b1d9-4c66-b6f0-3156921ef2f2)

bug fixed.  thanks for the work
