### ISSUE TITLE
Добавить возможность отклонения вакансии

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-cv#757]
### Problem description

У пользователя нет инфы, почему некоторые вакансии отклонены, а некоторые нет. При выгрузке все вакансии, которые были отклонены, отправляются в архив, что мешает собирать статистику.

### Proposed solution

Добавить новое состояние “Отклонено”, с указанием одного или нескольких причин отклонения (желательно готовые ответы-инпуты, если не получится - как-нибудь через текстовое поле). 

**причины отклонения вакаснии**

- Слишком высокие требования к опыту работы
- Неревантный стек технологий
- Слишком низкая заработная плата
- Вакансия конкурентов
- Требуется обязательное высшее образование или быть студентом ВУЗа

**Comment by usernaimandrey** [comment]
Могу взять в работу

**Comment by usernaimandrey** [comment]
В приложении есть система уведомлений, при том или ином событии создоется уведомление
Нужно ли создавать уведомление об публикации или отклонении резюме?
![Снимок экрана от 2024-07-08 01-42-53](https://github.com/Hexlet/hexlet-cv/assets/48034349/83e4b734-94c5-4bad-870c-64659c6ae720)

**Comment by fey** [comment]
Думаю почему бы и нет, давай использовать
