### ISSUE TITLE
Do not show commnts from other locales in sidebar

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-cv#765]
### Problem description

In enlish locale we can see russian comments. But if we click on it, we get 404 
https://cv.hexlet.io/resumes/7950#answer-6576
![image](https://github.com/user-attachments/assets/c7b2381e-ac52-4cc9-a6bb-4d882bf6808a)

![image](https://github.com/user-attachments/assets/c7b2381e-ac52-4cc9-a6bb-4d882bf6808a)

### Proposed solution

Filter comments and show it only for current locale

**Comment by fey** [comment]
@usernaimandrey can you do it?

**Comment by usernaimandrey** [comment]
https://github.com/Hexlet/hexlet-cv/pull/767
